import * as THREE from './vendor/three.module.js';
import {mergeGeometries} from './vendor/utils/BufferGeometryUtils.js';
const MAX_MARKS=96,MAX_SMOKE=96;
const vertex=`attribute float life; varying vec2 vUv; varying float vLife; void main(){vUv=uv;vLife=life;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.);}`;
const markFragment=`varying vec2 vUv;varying float vLife;void main(){vec2 p=vUv*2.-1.;float r=length(p);float a=atan(p.y,p.x);float edge=.77+.08*sin(a*9.)+.045*sin(a*17.);float chip=1.-smoothstep(edge-.13,edge,r);float hole=1.-smoothstep(.12,.27,r);float ridge=smoothstep(.2,.3,r)*(1.-smoothstep(.31,.43,r));vec3 color=mix(vec3(.038,.024,.023),vec3(.22,.15,.10),ridge*.6);gl_FragColor=vec4(color,(chip*.67+hole*.28)*vLife);}`;
const smokeFragment=`varying vec2 vUv;varying float vLife;void main(){vec2 p=vUv*2.-1.;float n=sin(p.x*12.+sin(p.y*8.))*sin(p.y*11.+sin(p.x*5.));float shape=1.-smoothstep(.22,.98,length(p)+n*.09);float alpha=shape*vLife*.21;if(alpha<.002)discard;gl_FragColor=vec4(vec3(.32,.27,.24),alpha);}`;
function poolMesh(count,name,fragment){const geometry=new THREE.PlaneGeometry(1,1);geometry.setAttribute('life',new THREE.InstancedBufferAttribute(new Float32Array(count),1));const material=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});const mesh=new THREE.InstancedMesh(geometry,material,count);mesh.name=name;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.count=count;return mesh;}
export class ImpactVFX{
 constructor(parent){this.root=new THREE.Group();this.root.name='SurfaceImpactFX';parent.add(this.root);this.marks=poolMesh(MAX_MARKS,'BallisticScars',markFragment);this.smoke=poolMesh(MAX_SMOKE,'ImpactDust',smokeFragment);this.root.add(this.marks,this.smoke);this.object=new THREE.Object3D();this.normal=new THREE.Vector3();this.forward=new THREE.Vector3(0,0,1);this.markCursor=0;this.smokeCursor=0;this.markPool=Array.from({length:MAX_MARKS},()=>({position:new THREE.Vector3(),rotation:new THREE.Quaternion(),age:99,duration:8,size:1}));this.smokePool=Array.from({length:MAX_SMOKE},()=>({position:new THREE.Vector3(),velocity:new THREE.Vector3(),age:99,duration:1,size:1,spin:0}));this.clear();}
 clear(){for(const p of [...this.markPool,...this.smokePool])p.age=99;for(const mesh of[this.marks,this.smoke]){mesh.geometry.attributes.life.array.fill(0);mesh.geometry.attributes.life.needsUpdate=true;}this.markCursor=this.smokeCursor=0;}
 burst(t){if(!['wall','floor'].includes(t.surface)||!t.normal)return;const p=this.markPool[this.markCursor++%MAX_MARKS];this.normal.set(t.normal.x,t.normal.z,t.normal.y).normalize();p.position.set(t.tx*4,t.tz*4,t.ty*4).addScaledVector(this.normal,.018);p.rotation.setFromUnitVectors(this.forward,this.normal);p.age=0;p.duration=7+(t.id%4);p.size=t.weapon===2?.32:.13+(t.id%4)*.017;
 for(let i=0;i<2;i++){const q=this.smokePool[this.smokeCursor++%MAX_SMOKE];q.position.copy(p.position);q.velocity.copy(this.normal).multiplyScalar(.2+i*.16);q.velocity.x+=Math.sin(t.id*2.399+i)*.13;q.velocity.z+=Math.cos(t.id*2.399+i)*.13;q.velocity.y+=.13;q.age=0;q.duration=.55+i*.25;q.size=.25+i*.15;q.spin=t.id*.37+i;}}
 update(dt,camera,reducedMotion=false){let marks=0,smoke=0;const stamp=(mesh,p,slot,scale,alpha)=>{this.object.position.copy(p.position);this.object.scale.setScalar(scale);this.object.updateMatrix();mesh.setMatrixAt(slot,this.object.matrix);mesh.geometry.attributes.life.setX(slot,alpha);};
 for(let i=0;i<MAX_MARKS;i++){const p=this.markPool[i];p.age+=dt;const alive=p.age<p.duration;this.object.quaternion.copy(p.rotation);stamp(this.marks,p,i,p.size,alive?Math.min(1,(p.duration-p.age)/2):0);if(alive)marks++;}
 for(let i=0;i<MAX_SMOKE;i++){const p=this.smokePool[i];p.age+=dt;const alive=p.age<p.duration&&!reducedMotion;if(alive){p.position.addScaledVector(p.velocity,dt);smoke++;}if(camera)camera.getWorldQuaternion(this.object.quaternion);else this.object.quaternion.identity();this.object.rotateZ(p.spin);const u=Math.min(1,p.age/p.duration);stamp(this.smoke,p,i,p.size*(1+u*2),alive?Math.sin(Math.PI*u)*(1-u):0);}
 for(const mesh of[this.marks,this.smoke]){mesh.instanceMatrix.needsUpdate=true;mesh.geometry.attributes.life.needsUpdate=true;}this.active={marks,smoke};}
 diagnostics(){return{...this.active,capacity:{marks:MAX_MARKS,smoke:MAX_SMOKE}};}
}
function merged(parts){const geometries=parts.map(([g,p,r])=>{const m=new THREE.Matrix4().compose(new THREE.Vector3(...p),new THREE.Quaternion().setFromEuler(new THREE.Euler(...r)),new THREE.Vector3(1,1,1));g.applyMatrix4(m);if(g.index){const flat=g.toNonIndexed();g.dispose();return flat;}return g;});const geometry=mergeGeometries(geometries,false);for(const g of geometries)g.dispose();return geometry;}
export class RocketVFX{
 constructor(parent){this.root=new THREE.Group();this.root.name='ReliquaryRocketFX';parent.add(this.root);this.object=new THREE.Object3D();this.direction=new THREE.Vector3();this.forward=new THREE.Vector3(0,0,-1);const parts=[[new THREE.CylinderGeometry(.075,.09,.42,12),[0,0,0],[Math.PI/2,0,0]]];for(let i=0;i<4;i++)parts.push([new THREE.BoxGeometry(.025,.23,.16),[0,0,.13],[0,0,i*Math.PI/2]]);const shell=merged(parts);const nose=new THREE.ConeGeometry(.08,.2,12);nose.rotateX(-Math.PI/2);nose.translate(0,0,-.31);const jet=new THREE.ConeGeometry(.09,.55,10);jet.rotateX(Math.PI/2);jet.translate(0,0,.46);const make=(g,m,name)=>{const mesh=new THREE.InstancedMesh(g,m,64);mesh.name=name;mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.root.add(mesh);return mesh;};this.shell=make(shell,new THREE.MeshStandardMaterial({color:0x55423b,metalness:.68,roughness:.5}),'RocketIronBody');this.nose=make(nose,new THREE.MeshStandardMaterial({color:0xc1a780,roughness:.75}),'RocketBoneTip');this.jet=make(jet,new THREE.MeshBasicMaterial({color:0xff622b,transparent:true,opacity:.66,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}),'RocketExhaust');}
 update(run){let i=0;for(const p of run.projectiles||[]){if(p.kind!=='rocket'||p.life<=0||i>=64)continue;this.direction.set(p.vx,p.vz,p.vy).normalize();this.object.quaternion.setFromUnitVectors(this.forward,this.direction);this.object.position.set(p.x*4,p.z*4,p.y*4);this.object.scale.setScalar(1);this.object.updateMatrix();this.shell.setMatrixAt(i,this.object.matrix);this.nose.setMatrixAt(i,this.object.matrix);this.object.scale.set(1,1,.8+Math.sin((p.age||0)*71)*.16);this.object.updateMatrix();this.jet.setMatrixAt(i,this.object.matrix);i++;}for(const m of[this.shell,this.nose,this.jet]){m.count=i;m.instanceMatrix.needsUpdate=true;}}
}
