import * as THREE from './vendor/three.module.js';
import {mergeGeometries} from './vendor/utils/BufferGeometryUtils.js';
const MAX_MARKS=96,MAX_SMOKE=96,MAX_SPLASH=96,MAX_SPLASH_DROPS=288;
const vertex=`attribute float life; attribute float seed; varying vec2 vUv; varying float vLife; varying float vSeed; void main(){vUv=uv;vLife=life;vSeed=seed;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.);}`;
const markFragment=`varying vec2 vUv;varying float vLife;void main(){vec2 p=vUv*2.-1.;float r=length(p);float a=atan(p.y,p.x);float edge=.77+.08*sin(a*9.)+.045*sin(a*17.);float chip=1.-smoothstep(edge-.13,edge,r);float hole=1.-smoothstep(.12,.27,r);float ridge=smoothstep(.2,.3,r)*(1.-smoothstep(.31,.43,r));vec3 color=mix(vec3(.038,.024,.023),vec3(.22,.15,.10),ridge*.6);gl_FragColor=vec4(color,(chip*.67+hole*.28)*vLife);}`;
const smokeFragment=`varying vec2 vUv;varying float vLife;void main(){vec2 p=vUv*2.-1.;float n=sin(p.x*12.+sin(p.y*8.))*sin(p.y*11.+sin(p.x*5.));float shape=1.-smoothstep(.22,.98,length(p)+n*.09);float alpha=shape*vLife*.21;if(alpha<.002)discard;gl_FragColor=vec4(vec3(.32,.27,.24),alpha);}`;
// Flesh hits get a wet, lobed radial burst rather than the old single red
// streak.  The mask is evaluated in the fragment shader so every pooled
// instance has a different edge without allocating textures or meshes.
const bloodFragment=`varying vec2 vUv;varying float vLife;varying float vSeed;void main(){vec2 p=vUv*2.-1.;float s=vSeed*6.283;float cs=cos(s),sn=sin(s);p=mat2(cs,-sn,sn,cs)*p;float r=length(p);float a=atan(p.y,p.x);float lobes=.14*sin(a*5.+s)+.075*sin(a*9.-s*1.7)+.04*sin(a*17.+.8);float body=1.-smoothstep(.22+lobes,.9+lobes,r);float cavity=smoothstep(.07,.2,r)*(1.-smoothstep(.3,.5,r));float stream=smoothstep(.55,.97,abs(p.x+sin(s)*.12))*smoothstep(-.12,.82,p.y);float satellite=1.-smoothstep(.05,.16,length(p-vec2(sin(s)*.42,cos(s)*.33)));float alpha=(body*.8+cavity*.3+stream*.32+satellite*.42)*vLife;if(alpha<.004)discard;vec3 wet=mix(vec3(.12,.004,.008),vec3(.62,.02,.035),clamp(1.-r+vSeed*.22,0.,1.));gl_FragColor=vec4(wet,alpha);}`;
function poolMesh(count,name,fragment){const geometry=new THREE.PlaneGeometry(1,1);geometry.setAttribute('life',new THREE.InstancedBufferAttribute(new Float32Array(count),1));geometry.setAttribute('seed',new THREE.InstancedBufferAttribute(new Float32Array(count),1));const material=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});const mesh=new THREE.InstancedMesh(geometry,material,count);mesh.name=name;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.count=count;return mesh;}
export class ImpactVFX{
 constructor(parent){this.root=new THREE.Group();this.root.name='SurfaceImpactFX';parent.add(this.root);this.marks=poolMesh(MAX_MARKS,'BallisticScars',markFragment);this.smoke=poolMesh(MAX_SMOKE,'ImpactDust',smokeFragment);this.splashes=poolMesh(MAX_SPLASH,'FleshImpactSplashes',bloodFragment);this.bloodDrops=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshPhysicalMaterial({color:0x9e1625,roughness:.22,metalness:.04,clearcoat:.32,clearcoatRoughness:.16,transparent:true,opacity:.9,depthWrite:false}),MAX_SPLASH_DROPS);this.bloodDrops.name='FleshImpactDroplets';this.bloodDrops.frustumCulled=false;this.bloodDrops.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.root.add(this.marks,this.smoke,this.splashes,this.bloodDrops);this.object=new THREE.Object3D();this.normal=new THREE.Vector3();this.forward=new THREE.Vector3(0,0,1);this.markCursor=0;this.smokeCursor=0;this.splashCursor=0;this.dropCursor=0;this.markPool=Array.from({length:MAX_MARKS},()=>({position:new THREE.Vector3(),rotation:new THREE.Quaternion(),age:99,duration:8,size:1}));this.smokePool=Array.from({length:MAX_SMOKE},()=>({position:new THREE.Vector3(),velocity:new THREE.Vector3(),age:99,duration:1,size:1,spin:0}));this.splashPool=Array.from({length:MAX_SPLASH},()=>({position:new THREE.Vector3(),rotation:new THREE.Quaternion(),age:99,duration:1,size:.16}));this.dropPool=Array.from({length:MAX_SPLASH_DROPS},()=>({position:new THREE.Vector3(),velocity:new THREE.Vector3(),age:99,duration:.8,size:.012,spin:0}));this.clear();}
 clear(){for(const p of [...this.markPool,...this.smokePool,...this.splashPool,...this.dropPool])p.age=99;for(const mesh of[this.marks,this.smoke,this.splashes]){mesh.geometry.attributes.life.array.fill(0);mesh.geometry.attributes.seed.array.fill(0);mesh.geometry.attributes.life.needsUpdate=true;mesh.geometry.attributes.seed.needsUpdate=true;}this.markCursor=this.smokeCursor=this.splashCursor=this.dropCursor=0;this.bloodDrops.count=0;}
 burst(t){
  const isSurface=t.surface==='wall'||t.surface==='floor';
  if(isSurface&&t.normal){const p=this.markPool[this.markCursor++%MAX_MARKS];this.normal.set(t.normal.x,t.normal.z,t.normal.y).normalize();p.position.set(t.tx*4,t.tz*4,t.ty*4).addScaledVector(this.normal,.018);p.rotation.setFromUnitVectors(this.forward,this.normal);p.age=0;p.duration=7+(t.id%4);p.size=t.weapon===2?.32:.13+(t.id%4)*.017;
   for(let i=0;i<2;i++){const q=this.smokePool[this.smokeCursor++%MAX_SMOKE];q.position.copy(p.position);q.velocity.copy(this.normal).multiplyScalar(.2+i*.16);q.velocity.x+=Math.sin(t.id*2.399+i)*.13;q.velocity.z+=Math.cos(t.id*2.399+i)*.13;q.velocity.y+=.13;q.age=0;q.duration=.55+i*.25;q.size=.25+i*.15;q.spin=t.id*.37+i;}}
  if(t.surface!=='flesh')return;
  const splash=this.splashPool[this.splashCursor++%MAX_SPLASH];
  const dx=(t.tx??t.x)- (t.x??0),dy=(t.ty??t.y)- (t.y??0),dz=(t.tz??t.z)- (t.z??0);
  this.normal.set(t.normal?.x??dx,t.normal?.z??dz,t.normal?.y??dy);
  if(this.normal.lengthSq()<.001)this.normal.set(0,1,0); else this.normal.normalize();
  splash.position.set((t.tx??t.x)*4,(t.tz??t.z)*4,(t.ty??t.y)*4).addScaledVector(this.normal,.025);
  splash.rotation.setFromUnitVectors(this.forward,this.normal);const seed=Math.abs(Math.sin((Number(t.id)||0)*12.9898))*1.0;splash.seed=seed;splash.rotation.multiply(new THREE.Quaternion().setFromAxisAngle(this.normal,seed*6.283));splash.age=0;splash.duration=1.05+seed*.42;splash.size=.14+seed*.1+(Number(t.weapon)%3)*.025;
  const tangent=new THREE.Vector3().crossVectors(this.normal,new THREE.Vector3(0,1,0));if(tangent.lengthSq()<.001)tangent.set(1,0,0);tangent.normalize();
  for(let i=0;i<9;i++){const q=this.dropPool[this.dropCursor++%MAX_SPLASH_DROPS],a=i*2.399+(Number(t.id)||0),side=Math.sin(a)*.23;q.position.copy(splash.position);q.velocity.copy(this.normal).multiplyScalar(.42+(i%4)*.16).addScaledVector(tangent,side).add(new THREE.Vector3(0,.16+(i%3)*.11,0));q.age=0;q.duration=.45+(i%5)*.11;q.size=.009+(i%3)*.004;q.spin=a;}
 }
 update(dt,camera,reducedMotion=false){let marks=0,smoke=0,splashes=0,drops=0;const stamp=(mesh,p,slot,scale,alpha)=>{this.object.position.copy(p.position);this.object.scale.setScalar(scale);this.object.updateMatrix();mesh.setMatrixAt(slot,this.object.matrix);mesh.geometry.attributes.life.setX(slot,alpha);if(mesh.geometry.attributes.seed)mesh.geometry.attributes.seed.setX(slot,p.seed||0);};
 for(let i=0;i<MAX_MARKS;i++){const p=this.markPool[i];p.age+=dt;const alive=p.age<p.duration;this.object.quaternion.copy(p.rotation);stamp(this.marks,p,i,p.size,alive?Math.min(1,(p.duration-p.age)/2):0);if(alive)marks++;}
 for(let i=0;i<MAX_SMOKE;i++){const p=this.smokePool[i];p.age+=dt;const alive=p.age<p.duration&&!reducedMotion;if(alive){p.position.addScaledVector(p.velocity,dt);smoke++;}if(camera)camera.getWorldQuaternion(this.object.quaternion);else this.object.quaternion.identity();this.object.rotateZ(p.spin);const u=Math.min(1,p.age/p.duration);stamp(this.smoke,p,i,p.size*(1+u*2),alive?Math.sin(Math.PI*u)*(1-u):0);}
 for(let i=0;i<MAX_SPLASH;i++){const p=this.splashPool[i];p.age+=dt;const alive=p.age<p.duration;this.object.quaternion.copy(p.rotation);stamp(this.splashes,p,i,p.size*(.78+p.age*.4),alive?Math.sin(Math.min(1,p.age/p.duration)*Math.PI)*(1-p.age/p.duration*.35):0);if(alive)splashes++;}
 for(let i=0;i<MAX_SPLASH_DROPS;i++){const p=this.dropPool[i];p.age+=dt;const alive=p.age<p.duration;if(alive&&!reducedMotion){p.velocity.y-=2.8*dt;p.position.addScaledVector(p.velocity,dt);drops++;}this.object.position.copy(p.position);this.object.rotation.set(p.spin*.7,p.spin*.43,p.spin);const fade=alive?Math.max(0,1-p.age/p.duration):0;this.object.scale.set(p.size*(.8+fade*.8),p.size*(1.2+fade*2.6),p.size*(.8+fade*.8));this.object.updateMatrix();this.bloodDrops.setMatrixAt(i,this.object.matrix);}this.bloodDrops.count=drops;
 for(const mesh of[this.marks,this.smoke,this.splashes,this.bloodDrops]){mesh.instanceMatrix.needsUpdate=true;if(mesh.geometry?.attributes?.life)mesh.geometry.attributes.life.needsUpdate=true;}
 // Keep the original diagnostics contract stable for existing telemetry while
 // retaining richer flesh-pool counts for local debugging.
 this.active={marks,smoke};this.detailActive={splashes,drops};}
 diagnostics(){return{...this.active,capacity:{marks:MAX_MARKS,smoke:MAX_SMOKE}};}
}
function merged(parts){const geometries=parts.map(([g,p,r])=>{const m=new THREE.Matrix4().compose(new THREE.Vector3(...p),new THREE.Quaternion().setFromEuler(new THREE.Euler(...r)),new THREE.Vector3(1,1,1));g.applyMatrix4(m);if(g.index){const flat=g.toNonIndexed();g.dispose();return flat;}return g;});const geometry=mergeGeometries(geometries,false);for(const g of geometries)g.dispose();return geometry;}
export class RocketVFX{
 constructor(parent){this.root=new THREE.Group();this.root.name='ReliquaryRocketFX';parent.add(this.root);this.object=new THREE.Object3D();this.direction=new THREE.Vector3();this.forward=new THREE.Vector3(0,0,-1);const parts=[[new THREE.CylinderGeometry(.075,.09,.42,12),[0,0,0],[Math.PI/2,0,0]]];for(let i=0;i<4;i++)parts.push([new THREE.BoxGeometry(.025,.23,.16),[0,0,.13],[0,0,i*Math.PI/2]]);const shell=merged(parts);const nose=new THREE.ConeGeometry(.08,.2,12);nose.rotateX(-Math.PI/2);nose.translate(0,0,-.31);const jet=new THREE.ConeGeometry(.09,.55,10);jet.rotateX(Math.PI/2);jet.translate(0,0,.46);const make=(g,m,name)=>{const mesh=new THREE.InstancedMesh(g,m,64);mesh.name=name;mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.root.add(mesh);return mesh;};this.shell=make(shell,new THREE.MeshStandardMaterial({color:0x55423b,metalness:.68,roughness:.5}),'RocketIronBody');this.nose=make(nose,new THREE.MeshStandardMaterial({color:0xc1a780,roughness:.75}),'RocketBoneTip');this.jet=make(jet,new THREE.MeshBasicMaterial({color:0xff622b,transparent:true,opacity:.66,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}),'RocketExhaust');}
 update(run){let i=0;for(const p of run.projectiles||[]){if(p.kind!=='rocket'||p.life<=0||i>=64)continue;this.direction.set(p.vx,p.vz,p.vy).normalize();this.object.quaternion.setFromUnitVectors(this.forward,this.direction);this.object.position.set(p.x*4,p.z*4,p.y*4);this.object.scale.setScalar(1);this.object.updateMatrix();this.shell.setMatrixAt(i,this.object.matrix);this.nose.setMatrixAt(i,this.object.matrix);this.object.scale.set(1,1,.8+Math.sin((p.age||0)*71)*.16);this.object.updateMatrix();this.jet.setMatrixAt(i,this.object.matrix);i++;}for(const m of[this.shell,this.nose,this.jet]){m.count=i;m.instanceMatrix.needsUpdate=true;}}
}
