import {makeCourse,makeCampaignCourse,newRun,tick,tickPlayer,shoot,parry,grapple,look,switchWeapon,addPeer,clamp,weapons} from './engine.js';
import {Renderer} from './renderer.js';
import {UI} from './ui.js';
import {PeerSession} from './peer.js';
import {AudioSystem} from './assets/audio.js';
const canvas=document.querySelector('#world');
const renderer=new Renderer(canvas),audio=new AudioSystem();
let run=newRun(makeCampaignCourse(0)),screen='menu',session=null,network='SOLO',settings={sensitivity:1,volume:.5,reducedMotion:false,gore:true,autoRun:false},last=0,acc=0,netClock=0,hudClock=0,frames=0,fps=60,fpsClock=0,remoteInput={},remoteSeen=0,remoteParry=0,parrySequence=0,remoteHook=0,hookSequence=0,snapshotSeq=0,lastSnapshot=-1,netEventSeq=0,lastNetEvent=-1,netEvents=[];
const keys=new Set(),touches=new Map(),pulses=new Set();let fire=false,alt=false,lastStep=0,lastHeartbeat=0;
const playerFields=['x','y','z','angle','pitch','vx','vy','vz','speed','distance','time','mode','health','energy','weapon','cooldowns','fireCooldown','shot','damage','heal','aim','slide','dashTime','punch','hookTime','hookCooldown','hookTarget','parryTime','parryCooldown','slam','wallJumps','style','styleTotal','styleLabel','rank','kills','combo','bestCombo','lastWeapon','repeat','coinCharges','coinRegen','altCooldown','respawnTime'];
const playerData=p=>Object.fromEntries(playerFields.map(k=>[k,p[k]]));
function snapshot(){return{seq:++snapshotSeq,host:playerData(run),guest:run.peer?playerData(run.peer):null,wave:run.wave,waveDelay:run.waveDelay,enemies:run.course.enemies,projectiles:run.projectiles,coins:run.coins,gore:run.gore.slice(-110),blood:run.blood,tracers:run.tracers,campaign:run.campaign,sectorIndex:run.sectorIndex,sectorCount:run.sectorCount,sectorId:run.sectorId,sectorName:run.sectorName,waveCount:run.waveCount,director:run.director?Object.fromEntries(['state','budget','spent','remainingBudget','aliveCap','active','pending','elapsed'].map(k=>[k,run.director[k]])):null,spawnTelegraphs:run.spawnTelegraphs||[],explosions:run.explosions||[],audioEvents:netEvents.slice(-20)};}
function releaseFormFocus(){const active=document.activeElement;if(active&&typeof active.blur==='function')active.blur();}
function resetInput(){releaseFormFocus();keys.clear();touches.clear();pulses.clear();fire=false;alt=false;}
function pointerLock(){if(screen==='play')audio.unlock().then(()=>{if(screen==='play'){audio.resume();audio.play('ambience');}});if(matchMedia('(pointer:coarse)').matches||document.pointerLockElement===canvas)return;try{canvas.requestPointerLock()?.catch(()=>ui.toast('Click the arena to capture your mouse. Arrow keys also aim.'));}catch{}}
function configure(value){settings={...settings,...value};run.autoRun=!!settings.autoRun;renderer.setSettings?.(settings);audio.setVolume(settings.volume);audio.setMuted(settings.volume===0);}
function begin(coop=false){if(!coop&&session?.connected){session.close();session=null;network='SOLO';}run=newRun(makeCampaignCourse(0));run.mode='play';run.autoRun=!!settings.autoRun;if(coop)addPeer(run);screen='play';acc=0;netEvents=[];resetInput();remoteInput={};remoteParry=0;remoteHook=0;parrySequence=0;hookSequence=0;remoteSeen=performance.now();ui.play?.();ui.hide?.();document.body.classList.add('playing');audio.unlock().then(()=>{if(screen!=='play')return;audio.resume();audio.play('ambience');});pointerLock();if(coop)session.send({t:'start',s:snapshot()});ui.toast('DESCENT 01 // THE BLOODWORKS');}
function pause(){if(screen!=='play')return;screen='pause';resetInput();document.exitPointerLock?.();if(!session?.connected)run.mode='pause';audio.pause();ui.pause();if(session?.connected)ui.toast('Co-op stays live while your menu is open.');}
function resume(){if(screen!=='pause')return;screen='play';run.mode='play';ui.play?.();ui.hide?.();document.body.classList.add('playing');audio.unlock().then(()=>{if(screen!=='play')return;audio.resume();audio.play('ambience');});pointerLock();}
function menu(){resetInput();document.exitPointerLock?.();audio.pause();screen='menu';run.mode='ready';session?.close();session=null;network='SOLO';run=newRun(makeCampaignCourse(0));ui.menu();document.body.classList.remove('playing');}
function restart(){if(session?.connected&&session.role==='guest'){session.send({t:'restart-request'});ui.toast('Restart requested from host.');return;}begin(!!session?.connected);}
function disconnected(){network='DISCONNECTED';ui.networkStatus(network);resetInput();if(session?.role==='guest'){screen='pause';run.mode='pause';audio.pause();document.exitPointerLock?.();ui.pause();ui.toast('Host disconnected. Start solo to continue in a fresh arena.');}else if(run.peer){delete run.peer;ui.toast('Partner disconnected. Continuing solo.');}}
function makeSession(){session?.close();session=new PeerSession({onStatus:text=>{network=text;ui.networkStatus(text);},onMessage:receive,onConnect:()=>{network='P2P CONNECTED';ui.networkStatus(network);if(session.role==='host')begin(true);else ui.toast('Connected. Waiting for host arena…');},onDisconnect:disconnected});return session;}
const ui=new UI({onStart:()=>begin(false),onPause:pause,onResume:resume,onRestart:restart,onMenu:menu,onSettings:configure,onHost:async()=>{try{ui.setOffer(await makeSession().host());}catch(e){ui.networkStatus(e.message);}},onJoin:async code=>{try{ui.setAnswer(await makeSession().join(code));}catch(e){ui.networkStatus(e.message);}},onAccept:async code=>{try{await session.accept(code);}catch(e){ui.networkStatus(e.message);}},onDisconnect:()=>{const wasGuest=session?.role==='guest';session?.close();session=null;network='SOLO';if(run.peer)delete run.peer;if(wasGuest&&screen==='play'){screen='pause';run.mode='pause';ui.pause();}ui.networkStatus(network);}});
function saneSnapshot(s){return s&&Number.isInteger(s.seq)&&Number.isInteger(s.sectorIndex)&&s.sectorIndex>=0&&s.sectorIndex<3&&s.host&&s.guest&&Array.isArray(s.enemies)&&s.enemies.length<=96&&['projectiles','coins','gore','blood','tracers','spawnTelegraphs','explosions'].every(k=>Array.isArray(s[k])&&s[k].length<=250)&&[s.host,s.guest].every(p=>['x','y','z','angle','pitch','health'].every(k=>Number.isFinite(p[k]))&&p.x>=0&&p.x<=12&&p.y>=0&&p.y<=12);}
function applySnapshot(s,start=false){if(!saneSnapshot(s)||s.seq<=lastSnapshot)return;lastSnapshot=s.seq;const oldHealth=run.health,oldKills=run.kills;if(start){parrySequence=0;hookSequence=0;run=newRun(makeCampaignCourse(0));run.mode='play';screen='play';resetInput();ui.play?.();ui.hide?.();document.body.classList.add('playing');audio.unlock().then(()=>{if(screen!=='play')return;audio.resume();audio.play('ambience');});pointerLock();}const changedSector=run.course.index!==s.sectorIndex;if(changedSector)run.course=makeCampaignCourse(s.sectorIndex);for(const key of ['campaign','sectorIndex','sectorCount','sectorId','sectorName','waveCount','director'])run[key]=s[key];const previous={x:run.x,y:run.y,z:run.z,angle:run.angle,pitch:run.pitch};for(const k of playerFields)if(s.guest[k]!==undefined)run[k]=s.guest[k];if(!start&&!changedSector&&screen==='play'&&Math.hypot(previous.x-run.x,previous.y-run.y)<.5&&run.health>0){run.x=previous.x+(run.x-previous.x)*.25;run.y=previous.y+(run.y-previous.y)*.25;run.angle=previous.angle;run.pitch=previous.pitch;}run.mode=s.host.mode;run.peer=s.host;run.course.enemies=s.enemies;run.wave=s.wave;run.waveDelay=s.waveDelay;for(const key of ['projectiles','coins','gore','blood','tracers','spawnTelegraphs','explosions'])run[key]=s[key];run.kills=s.host.kills;run.autoRun=!!settings.autoRun;if(oldHealth>run.health)audio.play('damage');if(oldKills<run.kills)audio.play('kill');if(Array.isArray(s.audioEvents))for(const e of s.audioEvents.slice(-20)){if(Number.isSafeInteger(e.seq)&&e.seq>lastNetEvent){lastNetEvent=e.seq;audio.play(e.type,e.weapon??0,spatialEvent(e));}}if(changedSector)ui.toast('DESCENT '+(run.sectorIndex+1)+' // '+run.sectorName.toUpperCase());}
function receive(msg){if(!msg||typeof msg.t!=='string')return;if(session?.role==='host'){if(msg.t==='input'){const n=msg.i;if(!n||!Number.isFinite(n.angle)||!Number.isFinite(n.pitch))return;remoteInput={forward:clamp(Number(n.forward)||0,-1,1),strafe:clamp(Number(n.strafe)||0,-1,1),jump:!!n.jump,dash:!!n.dash,slide:!!n.slide,fire:!!n.fire,alt:!!n.alt,angle:clamp(n.angle,-Math.PI,Math.PI),pitch:clamp(n.pitch,-1.35,1.35),weapon:clamp(Math.floor(Number(n.weapon)||0),0,weapons.length-1),parry:Number.isSafeInteger(n.parry)?n.parry:0,hook:Number.isSafeInteger(n.hook)?n.hook:0};remoteSeen=performance.now();}if(msg.t==='restart-request')ui.toast('Partner requests restart. Esc → Restart arena.');}else if(msg.t==='start'){lastSnapshot=-1;lastNetEvent=-1;applySnapshot(msg.s,true);}else if(msg.t==='snapshot')applySnapshot(msg.s);}
function intent(){if(screen!=='play')return{};const held=[...touches.values()].map(v=>v.action),has=a=>held.includes(a);return{forward:(Number(keys.has('KeyW')||has('forward'))-Number(keys.has('KeyS')||has('back')))||(settings.autoRun?1:0),strafe:Number(keys.has('KeyD')||has('right'))-Number(keys.has('KeyA')||has('left')),jump:keys.has('Space')||has('jump')||pulses.has('jump'),dash:keys.has('ShiftLeft')||keys.has('ShiftRight')||has('dash')||pulses.has('dash'),slide:keys.has('ControlLeft')||keys.has('ControlRight')||has('slide'),turn:Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft')),lookY:Number(keys.has('ArrowUp'))-Number(keys.has('ArrowDown')),fire:fire||has('fire')||pulses.has('fire'),alt:alt||has('alt')||pulses.has('alt'),angle:run.angle,pitch:run.pitch,weapon:run.weapon,parry:parrySequence,hook:hookSequence};}
function punch(){if(screen!=='play')return;parrySequence++;if(session?.role==='guest'&&session.connected){run.punch=.3;audio.play('parry');}else parry(run);}
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.code==='Escape'){e.preventDefault();screen==='play'?pause():screen==='pause'?resume():null;return;}if(screen!=='play')return;if(['Space','ControlLeft','ControlRight','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Space')pulses.add('jump');if(e.code==='ShiftLeft'||e.code==='ShiftRight')pulses.add('dash');if(/^Digit[1234]$/.test(e.code))switchWeapon(run,Number(e.code.at(-1))-1);if(e.code==='KeyF')punch();if(e.code==='KeyE'){hookSequence++;if(session?.role!=='guest'||!session.connected)grapple(run);}if(e.code==='KeyR')restart();});
addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(screen!=='play')return;if(e.pointerType==='touch'){touches.set(e.pointerId,{action:'look',x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);}else if(document.pointerLockElement===canvas){if(e.button===0){fire=true;pulses.add('fire');}if(e.button===2){alt=true;pulses.add('alt');}}else pointerLock();});
addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&screen==='play')look(run,e.movementX*settings.sensitivity,e.movementY*settings.sensitivity);});
canvas.addEventListener('pointermove',e=>{const t=touches.get(e.pointerId);if(t?.action==='look'){look(run,(e.clientX-t.x)*1.8*settings.sensitivity,(e.clientY-t.y)*1.8*settings.sensitivity);t.x=e.clientX;t.y=e.clientY;}});
document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('[data-action]');if(!b||screen!=='play')return;e.preventDefault();const a=b.dataset.action;if(['fire','alt','jump','dash'].includes(a))pulses.add(a);if(a==='parry'){punch();return;}if(a==='hook'){hookSequence++;if(session?.role!=='guest'||!session.connected)grapple(run);return;}if(a==='weapon'){switchWeapon(run,(run.weapon+1)%weapons.length);return;}touches.set(e.pointerId,{action:a});b.setPointerCapture(e.pointerId);});
const release=e=>{touches.delete(e.pointerId);if(e.pointerType!=='touch'){if(e.button===0)fire=false;if(e.button===2)alt=false;}};addEventListener('pointerup',release);addEventListener('pointercancel',release);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{if(screen!=='play')return;e.preventDefault();switchWeapon(run,(run.weapon+(e.deltaY>0?1:weapons.length-1))%weapons.length);},{passive:false});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&screen==='play')pause();});addEventListener('blur',()=>{resetInput();if(screen==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='play')pause();});addEventListener('resize',()=>renderer.resize());
const spatialEvent=e=>Number.isFinite(e.x)&&Number.isFinite(e.y)?{...e,position:{x:e.x*4,y:(e.z||0)*4,z:e.y*4}}:e;
function processEvents(){if(run.distance<lastStep)lastStep=0;if(run.time<lastHeartbeat)lastHeartbeat=0;if(run.distance-lastStep>.4&&run.z<.02&&run.slide<.3){lastStep=run.distance;audio.play('footstep');}if(run.health>0&&run.health<35&&run.time-lastHeartbeat>.8){lastHeartbeat=run.time;audio.play('heartbeat');}audio.updateListener?.({x:run.x*4,y:(run.z+.4)*4,z:run.y*4,forwardX:Math.cos(run.angle)*Math.cos(run.pitch),forwardY:Math.sin(run.pitch),forwardZ:Math.sin(run.angle)*Math.cos(run.pitch)});for(const e of [...run.events,...(run.peer?.events||[])]){audio.play(e.type,e.weapon??run.weapon,spatialEvent(e));if(e.type==='wave')ui.toast('WAVE '+e.wave+' / '+(run.waveCount||3)+' — INCOMING');if(e.type==='sector-transition')ui.toast('DESCENT '+(e.sectorIndex+1)+' // '+e.sectorName.toUpperCase());if(session?.role==='host'&&['enemy-attack','explosion','spawn','wave','sector-transition'].includes(e.type)){netEvents.push({...e,seq:++netEventSeq});netEvents=netEvents.slice(-20);}if(e.type==='parry')ui.toast('+ PARRY');if(e.type==='kill'||e.type==='hit')ui.hit?.();}run.events.length=0;if(run.peer?.events)run.peer.events.length=0;}
function frame(t){const dt=Math.min(.1,last?(t-last)/1000:0);last=t;frames++;fpsClock+=dt;if(fpsClock>.75){fps=frames/fpsClock;frames=0;fpsClock=0;}const live=screen==='play'||(session?.connected&&screen==='pause');if(live&&run.mode==='play'){acc=Math.min(acc+dt,.1);const i=intent();let stepped=false;while(acc>=1/120){stepped=true;if(session?.connected&&session.role==='guest'){tickPlayer(run,1/120,i);if(i.fire||i.alt){if(run.cooldowns[run.weapon]<=0){run.shot=1;run.cooldowns[run.weapon]=weapons[run.weapon].interval;audio.play('shot',run.weapon);}}}else{if(i.fire||i.alt)shoot(run,i.alt);if(run.peer){const ri=performance.now()-remoteSeen<350?remoteInput:{};if(Number.isFinite(ri.angle)){run.peer.angle=ri.angle;run.peer.pitch=ri.pitch;switchWeapon(run.peer,ri.weapon);}tickPlayer(run.peer,1/120,ri);if(ri.fire||ri.alt)shoot(run.peer,ri.alt);if(ri.parry>remoteParry){remoteParry=ri.parry;parry(run.peer);}if(ri.hook>remoteHook){remoteHook=ri.hook;grapple(run.peer);}}tick(run,1/120,i);}acc-=1/120;}if(stepped&&(!session?.connected||session.role==='host'))pulses.clear();netClock+=dt;if(session?.connected&&netClock>=.05){netClock=0;if(session.role==='host')session.send({t:'snapshot',s:snapshot()});else{session.send({t:'input',i:{...i,angle:run.angle,pitch:run.pitch}});pulses.clear();}}processEvents();}
 if(['win','dead'].includes(run.mode)&&!['win','dead'].includes(screen)){screen=run.mode;resetInput();document.exitPointerLock?.();audio.pause();ui.finish(run,run.mode==='win');if(session?.role==='host'&&session.connected)session.send({t:'snapshot',s:snapshot()});}
 renderer.render(run,t);hudClock+=dt;if(hudClock>=1/30){hudClock=0;ui.hud(run,{network:session?.connected?'P2P / '+Math.round(session.rtt||0)+' MS':network,fps});}requestAnimationFrame(frame);}
configure(settings);ui.menu();requestAnimationFrame(frame);
if(new URLSearchParams(location.search).has('debug'))window.__DEAD_ARRIVAL__={get run(){return run;},get screen(){return screen;},get session(){return session;},get fps(){return fps;},renderer,audio,begin,pause,resume,snapshot,receive,ui};
