import assert from 'node:assert/strict';
import{createRequire}from'node:module';import{mkdir,writeFile}from'node:fs/promises';
const{chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_PATH||'playwright');const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});
try{const p=await b.newPage({viewport:{width:512,height:320}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto('http://127.0.0.1:5200/tests/fixtures/lighting.html',{waitUntil:'domcontentloaded',timeout:120000});
 const rows=await p.evaluate(async()=>{
  const T=await import('/vendor/three.module.js'),{TransmissionRegion}=await import('/transmission-region.js'),g=new T.WebGLRenderer({canvas:document.querySelector('canvas')}),scene=new T.Scene(),camera=new T.PerspectiveCamera(60,1.6,.1,100);g.setSize(512,320);scene.background=new T.Color(0x552211);camera.position.z=5;
  scene.add(new T.HemisphereLight(0xffffff,0x444444,3));for(let i=0;i<9;i++){const mesh=new T.Mesh(new T.BoxGeometry(.8,4,.2),new T.MeshStandardMaterial({color:i%2?0x1133ee:0xeebb22,roughness:.6}));mesh.position.set((i-4)*.9,0,-1);scene.add(mesh);}
  const material=new T.MeshPhysicalMaterial({color:0xffffff,roughness:.16,transmission:.85,ior:1.5,thickness:0}),glass=new T.Mesh(new T.SphereGeometry(.5,32,24),material);glass.position.set(1,-.7,1);scene.add(glass);const region=new TransmissionRegion(g);region.refresh(scene);const target=new T.WebGLRenderTarget(512,320),before=new Uint8Array(512*320*4),after=new Uint8Array(before.length),rows=[];
  try{g.setRenderTarget(target);for(const[roughness,thickness,x]of[[.08,0,1],[.22,0,-1],[.5,0,1.7],[.15,.5,.7],[.22,3,0]]){material.roughness=roughness;material.thickness=thickness;glass.position.x=x;g.render(scene,camera);g.readRenderTargetPixels(target,0,0,512,320,before);region.begin(camera);try{g.render(scene,camera);}finally{region.end();}g.readRenderTargetPixels(target,0,0,512,320,after);let max=0,changed=0;for(let i=0;i<before.length;i++){const d=Math.abs(before[i]-after[i]);max=Math.max(max,d);if(d>2)changed++;}rows.push({roughness,thickness,x,coverage:region.coverage,max,changed});}}finally{g.setRenderTarget(null);target.dispose();region.dispose();g.dispose();}return rows;
 });assert.deepEqual(errors,[]);assert.ok(rows.every(r=>r.max<=3&&r.changed<64),'conservative transmission bounds must preserve pixels');assert.ok(rows.some(r=>r.coverage<.4),'thin smooth glass should restrict the extra pass');await mkdir('.logs',{recursive:true});await writeFile('.logs/transmission-region.json',JSON.stringify({rows,errors},null,2));console.log(JSON.stringify({rows,errors},null,2));
}finally{await b.close();}
