// Story mode: the descent.
//
// Five long layers, each authored as shaped rooms, corridors and explicit
// openings. Room profiles let the footprint follow its role: arenas flare
// around their set pieces, galleries get side bays, and the narrow service
// spaces keep their own proportions. The compiler turns this into the
// engine's cell bitfield.
//
// Conventions
//   * one unit is a gameplay cell (4 m); x runs east, z runs south,
//   * the player enters from the south edge and descends at the north edge,
//   * a door/gate/vent is a real collision barrier in the sealed state,
//   * an arch or stair is always walkable,
//   * rooms never connect by accident: every threshold is listed below.
//
// Cover uses patterns instead of per-cell lists:
//   colonnade · corners · center · rows · ring · pillars · checker · edge

const ROOM_SHAPE_BY_KIND = Object.freeze({
  entry: 'threshold',
  hub: 'crossing',
  arena: 'octagon',
  ward: 'bay',
  hall: 'gallery',
  loop: 'aisle',
  vault: 'bastion',
  side: 'alcove',
  secret: 'square',
  exit: 'throat',
});

const room = (id, name, kind, rect, extra = {}) => ({
  id,
  name,
  kind,
  rect,
  shape: extra.shape || ROOM_SHAPE_BY_KIND[kind] || 'chamfer',
  ...extra,
});
const corr = (id, points, width = 2.4, kind = 'hall', extra = {}) => ({ id, points, width, kind, ...extra });
const open = (id, roomId, side, at, width = 3, kind = 'arch', extra = {}) => ({ id, room: roomId, side, at, width, kind, ...extra });
const light = (anchor, color, intensity, role) => ({ anchor, color, intensity, role });
const prop = (id, kind, at, count = 4, spread = 2, extra = {}) => ({ id, kind, at, count, spread, ...extra });
const trail = (id, kind, points, count = 10, extra = {}) => ({ id, kind, points, count, ...extra });
const scare = (id, kind, at, note, extra = {}) => ({ id, kind, at, note, ...extra });
const piece = (id, type, extra = {}) => ({ id, type, ...extra });

export const DUNGEON_LAYERS = Object.freeze([
  // ---------------------------------------------------------------------------
  // FLOOR 01 — INTAKE FOUNDRY
  // Entry bay -> foundry hall with west/east work rooms -> pulse court ->
  // furnace key vault -> gated exit spine. Two western routes loop into the
  // ward so the level can be re-entered from either side of the hall.
  {
    id: 'f1-intake-foundry',
    index: 0,
    depth: 1,
    name: 'Intake Foundry',
    tag: 'FLOOR 01 // MATERIAL RECOVERY',
    act: 'Act I',
    theme: 'bloodworks',
    color: '#ff735e',
    width: 34,
    height: 24,
    entry: { x: 17.5, z: 21.5, angle: -Math.PI / 2 },
    exit: { x: 17.5, z: 2.5 },
    rooms: [
      room('f1-entry', 'Intake Gate', 'entry', [13, 20, 8, 3], {
        note: 'Wide spawn bay with the sealed pressure door on the west wall.',
        encounter: { tier: 1, budget: 5, maxAlive: 4, composition: { stalker: 2, caster: 1 }, tactic: 'Read the intake threshold before pushing north.' },
      }),
      room('f1-hall', 'Foundry Hall', 'hub', [8, 12, 18, 4], {
        coverPatterns: ['colonnade'],
        note: 'Main circulation hall: three exits north, one west, one east.',
        encounter: { tier: 2, budget: 9, maxAlive: 5, composition: { skitter: 2, bloodhound: 2, caster: 1 }, tactic: 'Hold the hall and rotate through the west service lane.' },
      }),
      room('f1-ward', 'Graft Ward', 'ward', [2, 11, 5, 6], {
        coverPatterns: ['corners'],
        encounter: { tier: 2, budget: 6, maxAlive: 4, composition: { skitter: 2, caster: 1 }, tactic: 'Clear the ward before the vault.' },
      }),
      room('f1-pump', 'Pump Bank', 'ward', [27, 10, 5, 7], {
        coverPatterns: [{ type: 'rows', every: 3, length: 2 }],
        encounter: { tier: 3, budget: 9, maxAlive: 5, composition: { brute: 1, bloodhound: 1, caster: 2 }, tactic: 'Break the pump line from the entry side.' },
      }),
      room('f1-court', 'Pulse Court', 'arena', [13, 5, 9, 5], {
        coverPatterns: ['center', 'corners'],
        hero: true,
        encounter: { tier: 3, budget: 14, maxAlive: 6, composition: { brute: 2, hexer: 1, bloodhound: 1, caster: 1 }, tactic: 'Use the pulse engine as hard cover; the court seals until it is cleared.' },
      }),
      room('f1-vault', 'Furnace Vault', 'vault', [3, 3, 7, 5], {
        coverPatterns: [{ type: 'ring', inset: 2, step: 2 }],
        encounter: { tier: 2, budget: 7, maxAlive: 4, composition: { caster: 2, skitter: 1 }, tactic: 'The foundry key sits in the furnace cage.' },
      }),
      room('f1-crane', 'Crane Gallery', 'hall', [24, 3, 7, 5], {
        coverPatterns: [{ type: 'edge', side: 's', run: 3 }],
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { bloodhound: 2, caster: 1 }, tactic: 'Cross under the gantry and take the court from the east.' },
      }),
      room('f1-nook', 'Maintenance Nook', 'secret', [30, 18, 3, 3], {
        note: 'Crawl-space cache behind the pump bank.',
        reward: 'armor shard',
      }),
      room('f1-sluice', 'Sluice', 'side', [2, 18, 5, 4], {
        encounter: { tier: 1, budget: 4, maxAlive: 3, composition: { skitter: 2 }, tactic: 'A quiet western start for players who skip the intake gate.' },
      }),
      room('f1-exit', 'Exit Spine', 'exit', [14, 1, 6, 3], {
        exitApproach: true,
        encounter: { tier: 1, budget: 0, maxAlive: 0, composition: {}, tactic: 'Ride the cargo lift down to the graft galleries.' },
      }),
    ],
    corridors: [
      corr('f1-c-intake', [[17, 19], [17, 16]], 2.6, 'hall'),
      corr('f1-c-hall-west', [[8, 14], [7, 14]], 2.4, 'service'),
      corr('f1-c-hall-east', [[25, 13], [26, 13]], 2.4, 'service'),
      corr('f1-c-court-west', [[13, 11], [13, 10]], 2.6, 'hall'),
      corr('f1-c-court-east', [[20, 11], [20, 10]], 2.6, 'hall'),
      corr('f1-c-court-vault', [[10, 5], [12, 5]], 2.4, 'service'),
      corr('f1-c-court-crane', [[23, 5], [22, 5]], 2.6, 'hall'),
      corr('f1-c-pump-crane', [[29, 9], [29, 8]], 2.4, 'service'),
      corr('f1-c-vault-run', [[3, 10], [3, 8]], 2.2, 'service'),
      corr('f1-c-sluice', [[12, 21], [7, 21]], 2.2, 'service'),
      corr('f1-c-sluice-ward', [[4, 17], [4, 17]], 2.2, 'service'),
      corr('f1-c-nook-vent', [[31, 17], [31, 17]], 1.6, 'vent'),
    ],
    openings: [
      open('f1-o-entry-n', 'f1-entry', 'n', 17, 4),
      open('f1-o-hall-s', 'f1-hall', 's', 17, 4),
      open('f1-o-entry-w', 'f1-entry', 'w', 21, 2),
      open('f1-o-sluice-e', 'f1-sluice', 'e', 21, 2),
      open('f1-o-sluice-n', 'f1-sluice', 'n', 4, 2),
      open('f1-o-ward-s', 'f1-ward', 's', 4, 2),
      open('f1-o-ward-e', 'f1-ward', 'e', 14, 3),
      open('f1-o-hall-w', 'f1-hall', 'w', 14, 3),
      open('f1-o-hall-e', 'f1-hall', 'e', 13, 3),
      open('f1-o-pump-w', 'f1-pump', 'w', 13, 3),
      open('f1-o-ward-n', 'f1-ward', 'n', 3, 2),
      open('f1-o-vault-s', 'f1-vault', 's', 3, 2),
      open('f1-o-vault-e', 'f1-vault', 'e', 5, 2),
      open('f1-o-hall-n-west', 'f1-hall', 'n', 13, 3),
      open('f1-o-court-s-west', 'f1-court', 's', 13, 3, 'door', { lockedBy: 'room-clear' }),
      open('f1-o-hall-n-east', 'f1-hall', 'n', 20, 3),
      open('f1-o-court-s-east', 'f1-court', 's', 20, 3, 'door', { lockedBy: 'room-clear' }),
      open('f1-o-court-w', 'f1-court', 'w', 5, 2, 'door', { lockedBy: 'room-clear' }),
      open('f1-o-court-e', 'f1-court', 'e', 5, 3, 'door', { lockedBy: 'room-clear' }),
      open('f1-o-crane-w', 'f1-crane', 'w', 5, 3),
      open('f1-o-pump-n', 'f1-pump', 'n', 29, 2),
      open('f1-o-crane-s', 'f1-crane', 's', 29, 2),
      open('f1-o-pump-s', 'f1-pump', 's', 31, 1),
      open('f1-o-nook-n', 'f1-nook', 'n', 31, 1, 'vent', { secret: true }),
      open('f1-o-court-n', 'f1-court', 'n', 17, 3),
      open('f1-o-exit-s', 'f1-exit', 's', 17, 3, 'gate', { key: 'f1-foundry-key', lockedBy: 'key' }),
    ],
    keys: [
      { id: 'f1-foundry-key', name: 'Foundry Key', at: [6, 4], roomId: 'f1-vault', opens: ['f1-o-exit-s'], note: 'Opens the exit spine gate.' },
    ],
    landmarks: [
      { id: 'f1-intake-gate', type: 'gate-organ', anchor: [17, 21], size: [4.6, 2.4, 1.4], material: 'iron-blood', animated: 'breath', playerFacing: true, roomId: 'f1-entry' },
      { id: 'f1-pulse-engine', type: 'organ-pump', anchor: [17, 7], size: [3.4, 4.6, 3.4], material: 'flesh-steel', animated: 'pulse', hero: true, roomId: 'f1-court' },
      { id: 'f1-furnace-heart', type: 'boiler-stack', anchor: [5, 5], size: [3.2, 3.5, 2.4], material: 'iron-amber', animated: 'steam', hero: true, roomId: 'f1-vault' },
      { id: 'f1-graft-conduit', type: 'flesh-conduit', anchor: [4, 13], size: [2.2, 4.1, 1.8], material: 'flesh-rust', animated: 'drip', roomId: 'f1-ward' },
      { id: 'f1-pump-bank', type: 'pump-bank', anchor: [29, 12], size: [2.4, 3.4, 2], material: 'iron-blood', animated: 'throb', roomId: 'f1-pump' },
      { id: 'f1-crane-gantry', type: 'gantry', anchor: [27, 4], size: [7.2, 3.2, 2], material: 'iron-amber', animated: 'sway', roomId: 'f1-crane' },
      { id: 'f1-sluice-valve', type: 'pump-bank', anchor: [4, 20], size: [2, 2.6, 1.6], material: 'iron-blood', animated: 'throb', roomId: 'f1-sluice' },
      { id: 'f1-exit-lift', type: 'chain-lift', anchor: [17, 2], size: [3.2, 4, 2.4], material: 'iron-amber', animated: 'ratchet', roomId: 'f1-exit' },
    ],
    machinery: [
      { id: 'f1-court-hoist', type: 'hanging-hoist', anchor: [17, 8], span: [2.4, 2.4], motion: 'pendulum', payload: 'heart' },
      { id: 'f1-west-pump', type: 'pump-bank', anchor: [3, 14], span: [1.6, 3.1], motion: 'throb', pipes: 3 },
      { id: 'f1-east-pump', type: 'pump-bank', anchor: [30, 14], span: [1.6, 3.1], motion: 'throb', pipes: 3 },
      { id: 'f1-crane-winches', type: 'winch-bank', anchor: [27, 6], span: [2.6, 1.8], motion: 'counterweight', cables: 4 },
    ],
    lights: [
      light([17, 20], '#ff3d36', 3.2, 'entry'),
      light([17, 13], '#cc2c37', 2.4, 'hall'),
      light([4, 13], '#cc2c37', 1.8, 'ward'),
      light([29, 12], '#cc2c37', 1.8, 'pump'),
      light([17, 7], '#ff6b40', 3.8, 'court'),
      light([5, 5], '#ffad55', 3, 'vault'),
      light([27, 5], '#ffad55', 2.4, 'crane'),
      light([4, 20], '#ff3d36', 1.6, 'sluice'),
      light([17, 2], '#ffad55', 3, 'exit'),
      light([31, 19], '#43c98a', 1.4, 'secret'),
    ],
    spots: [
      [0, 16, 21, 'stalker'], [0, 18, 21, 'stalker'],
      [1, 11, 13, 'skitter'], [1, 23, 13, 'bloodhound'], [1, 17, 14, 'caster'],
      [2, 4, 12, 'skitter'], [2, 29, 11, 'brute'], [2, 27, 4, 'bloodhound'],
      [3, 15, 6, 'brute'], [3, 19, 8, 'hexer'], [3, 17, 6, 'bloodhound'],
      [1, 4, 20, 'skitter'],
    ].map(([id, x, z, variant]) => ({ id: `f1-spawn-${id}`, x, z, wave: id, variant })),
    dread: 'The foundry is still warm. Something in the pipes is keeping time with your pulse.',
    props: [
      prop('f1-gore-hall', 'gore', [17, 13], 7, 4),
      trail('f1-trail-entry', 'blood', [[17, 19], [17, 16]], 14),
      prop('f1-candles-entry', 'candle', [17, 21], 4, 3),
      prop('f1-corpses-ward', 'corpse', [4, 14], 3, 2),
      prop('f1-bones-vault', 'bones', [6, 5], 6, 3),
      prop('f1-crates-pump', 'crate', [29, 13], 5, 3),
      prop('f1-cages-crane', 'cage', [27, 5], 2, 2),
      prop('f1-sigil-court', 'sigil', [17, 7], 1, 1),
      prop('f1-webs-sluice', 'webs', [4, 20], 4, 2),
      prop('f1-fog-hall', 'fog', [12, 14], 3, 5),
      prop('f1-fog-pump', 'fog', [29, 12], 2, 4),
      prop('f1-skulls-vault', 'skull', [7, 4], 5, 3),
      prop('f1-skulls-court', 'skull', [19, 6], 6, 4),
      prop('f1-eyes-nook', 'eyes', [31, 19], 2, 1.4),
      prop('f1-eyes-dark', 'eyes', [24, 15], 2, 2),
      prop('f1-limbs-hall', 'limb', [16, 15], 5, 4),
      prop('f1-limbs-sluice', 'limb', [5, 19], 3, 2),
      prop('f1-altar-court', 'altar', [15, 7], 1, 1),
      prop('f1-barrels-pump', 'barrel', [29, 12], 9, 3.4),
      prop('f1-barrels-crane', 'barrel', [27, 5], 6, 3),
      prop('f1-barrels-sluice', 'barrel', [4, 19], 5, 2.4),
      prop('f1-bloodpile-hall', 'bloodpile', [17, 14], 4, 4),
      prop('f1-bodypile-vault', 'bodypile', [5, 4], 3, 2.4),
    ],
    signature: 'Working foundry: live pipe pressure, oil drums stacked in the pump bank, blood running into the floor grates.',
    wallpaper: 'blood-streaked panels, gore congealed in the panel seams, bone stacks in the cold rooms',
    scares: [
      scare('f1-scream-entry', 'scream', [17, 21], 'First step into the foundry: a scream over the PA, then silence.', { roomId: 'f1-entry' }),
      scare('f1-lights-hall', 'lights-out', [17, 13], 'Hall lights cut when the court doors seal; red maintenance only.', { roomId: 'f1-hall' }),
      scare('f1-swarm-pump', 'swarm', [29, 12], 'Pump bank coughs a skitter swarm out of the pipe mouths.', { roomId: 'f1-pump' }),
      scare('f1-collapse-sluice', 'collapse', [4, 19], 'The sluice ladder gives way behind you and seals the west route.', { roomId: 'f1-sluice' }),
      scare('f1-watcher-crane', 'watcher', [27, 4], 'Something stands under the gantry and never moves while you look at it.', { roomId: 'f1-crane' }),
      scare('f1-hunt-vault', 'hunt', [5, 5], 'Taking the key wakes one brute that walks straight at the vault door.', { roomId: 'f1-vault' }),
    ],
    setpieces: [
      piece('f1-sp-intake-tunnel', 'tunnel', { points: [[17, 19], [17, 16]], width: 2.2, height: 5.2, cue: 'red' }),
      piece('f1-sp-ward-bulkhead', 'bulkhead', { anchor: [4, 13], width: 2.4, height: 4.4, cue: 'red' }),
      piece('f1-sp-sluice-collapse', 'collapse', { anchor: [4, 17], size: [1.7, 1.5, 1.4], cue: 'amber' }),
      piece('f1-sp-vault-pressure', 'pressure-door', { anchor: [3, 9], width: 1.8, height: 5, cue: 'red' }),
      piece('f1-sp-nook-hatch', 'recovery-cluster', { anchor: [31, 17], width: 1.6, height: 4.4, cue: 'amber' }),
    ],
    connections: [
      { id: 'f1-to-f2', kind: 'lift', at: [17.5, 2], to: 'f2-graft-galleries', label: 'Cargo lift · Floor 02' },
    ],
  },

  // ---------------------------------------------------------------------------
  // FLOOR 02 — GRAFT GALLERIES
  // Four wards hang off a central crossing with a western and an eastern loop.
  // The surgery theater is the sealed arena; the scrub room holds the key to
  // the descent shaft.
  {
    id: 'f2-graft-galleries',
    index: 1,
    depth: 2,
    name: 'Graft Galleries',
    tag: 'FLOOR 02 // STERILE WARD',
    act: 'Act I',
    theme: 'bloodworks',
    color: '#ff9d6b',
    width: 36,
    height: 24,
    entry: { x: 18.5, z: 21.5, angle: -Math.PI / 2 },
    exit: { x: 18.5, z: 2.5 },
    rooms: [
      room('f2-entry', 'Sterile Intake', 'entry', [14, 20, 8, 3], {
        encounter: { tier: 2, budget: 6, maxAlive: 4, composition: { stalker: 2, caster: 1 }, tactic: 'Decontaminate the landing before the crossing.' },
      }),
      room('f2-hub', 'Gallery Crossing', 'hub', [14, 13, 8, 4], {
        coverPatterns: ['corners'],
        encounter: { tier: 3, budget: 10, maxAlive: 6, composition: { skitter: 3, bloodhound: 2, hexer: 1 }, tactic: 'The crossing is the hinge for both ward loops.' },
      }),
      room('f2-wardA', 'Ward A', 'ward', [4, 16, 6, 4], {
        coverPatterns: ['rows'],
        encounter: { tier: 2, budget: 6, maxAlive: 4, composition: { skitter: 2, caster: 1 }, tactic: 'Bed rows break the sightline from the door.' },
      }),
      room('f2-wardB', 'Ward B', 'ward', [4, 9, 6, 4], {
        coverPatterns: ['rows'],
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { bloodhound: 2, caster: 1 }, tactic: 'Fight north through the ward to reach the lobe.' },
      }),
      room('f2-wardC', 'Ward C', 'ward', [26, 16, 6, 4], {
        coverPatterns: ['rows'],
        encounter: { tier: 2, budget: 6, maxAlive: 4, composition: { skitter: 2, caster: 1 }, tactic: 'Mirror image of Ward A.' },
      }),
      room('f2-wardD', 'Ward D', 'ward', [26, 9, 6, 4], {
        coverPatterns: ['rows'],
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { brute: 1, bloodhound: 1, caster: 1 }, tactic: 'The east loop leads here before the theater.' },
      }),
      room('f2-theater', 'Surgery Theater', 'arena', [13, 5, 10, 5], {
        coverPatterns: ['center', 'corners'],
        hero: true,
        encounter: { tier: 4, budget: 15, maxAlive: 7, composition: { brute: 2, hexer: 1, bloodhound: 2, caster: 1 }, tactic: 'The sealed theater opens both ward loops; use the table as cover.' },
      }),
      room('f2-scrub', 'Scrub Room', 'vault', [25, 3, 5, 4], {
        coverPatterns: [{ type: 'edge', side: 'n', run: 3 }],
        encounter: { tier: 3, budget: 7, maxAlive: 5, composition: { caster: 2, skitter: 1 }, tactic: 'The surgical key hangs in the scrub room.' },
      }),
      room('f2-drawer', 'Morgue Drawer', 'secret', [10, 3, 3, 3], {
        note: 'Drawer cache behind the theater vent.',
        reward: 'coin charge',
      }),
      room('f2-exit', 'Descent Shaft', 'exit', [16, 1, 6, 3], {
        exitApproach: true,
        encounter: { tier: 1, budget: 0, maxAlive: 0, composition: {}, tactic: 'Take the shaft down to the ossuary.' },
      }),
    ],
    corridors: [
      corr('f2-c-intake', [[18, 19], [18, 17]], 2.6, 'hall'),
      corr('f2-c-west-spur', [[13, 17], [10, 17]], 2.4, 'hall'),
      corr('f2-c-east-spur', [[22, 17], [25, 17]], 2.4, 'hall'),
      corr('f2-c-west-riser', [[7, 15], [7, 13]], 2.2, 'service'),
      corr('f2-c-east-riser', [[29, 15], [29, 13]], 2.2, 'service'),
      corr('f2-c-theater', [[17, 12], [17, 10]], 2.6, 'hall'),
      corr('f2-c-scrub', [[23, 7], [24, 7]], 2.4, 'service'),
      corr('f2-c-east-loop', [[32, 17], [33, 17], [33, 8], [30, 8]], 2.2, 'loop'),
      corr('f2-c-west-loop', [[3, 17], [2, 17], [2, 8], [3, 8]], 2.2, 'loop'),
      corr('f2-c-exit', [[18, 5], [18, 4]], 2.6, 'hall'),
      // The theater end meets its walkable north face beyond the octagonal corner cut.
      corr('f2-c-vent', [[15, 4], [12, 4]], 1.6, 'vent'),
    ],
    openings: [
      open('f2-o-entry-n', 'f2-entry', 'n', 18, 4),
      open('f2-o-hub-s', 'f2-hub', 's', 18, 4),
      open('f2-o-hub-w', 'f2-hub', 'w', 17, 3),
      open('f2-o-wardA-e', 'f2-wardA', 'e', 17, 3),
      open('f2-o-hub-e', 'f2-hub', 'e', 17, 3),
      open('f2-o-wardC-w', 'f2-wardC', 'w', 17, 3),
      open('f2-o-wardA-n', 'f2-wardA', 'n', 7, 2),
      open('f2-o-wardB-s', 'f2-wardB', 's', 7, 2),
      open('f2-o-wardC-n', 'f2-wardC', 'n', 29, 2),
      open('f2-o-wardD-s', 'f2-wardD', 's', 29, 2),
      open('f2-o-wardA-w', 'f2-wardA', 'w', 17, 2),
      open('f2-o-wardB-w', 'f2-wardB', 'w', 10, 2),
      open('f2-o-wardC-e', 'f2-wardC', 'e', 17, 2),
      open('f2-o-wardD-e', 'f2-wardD', 'e', 10, 2),
      open('f2-o-hub-n', 'f2-hub', 'n', 17, 4, 'door', { lockedBy: 'room-clear' }),
      open('f2-o-theater-s', 'f2-theater', 's', 17, 4, 'door', { lockedBy: 'room-clear' }),
      open('f2-o-theater-e', 'f2-theater', 'e', 7, 3),
      open('f2-o-scrub-w', 'f2-scrub', 'w', 7, 2),
      open('f2-o-scrub-e', 'f2-scrub', 'e', 5, 2),
      open('f2-o-theater-n', 'f2-theater', 'n', 18, 3, 'gate', { key: 'f2-surgical-key', lockedBy: 'key' }),
      open('f2-o-exit-s', 'f2-exit', 's', 18, 3),
      open('f2-o-theater-vent', 'f2-theater', 'n', 15, 1, 'vent', { secret: true }),
      open('f2-o-drawer-e', 'f2-drawer', 'e', 4, 1),
    ],
    keys: [
      { id: 'f2-surgical-key', name: 'Surgical Key', at: [27, 5], roomId: 'f2-scrub', opens: ['f2-o-theater-n'], note: 'Opens the descent shaft gate.' },
    ],
    landmarks: [
      { id: 'f2-gallery-gate', type: 'gate-organ', anchor: [18, 21], size: [4.2, 2.2, 1.3], material: 'iron-blood', animated: 'breath', playerFacing: true, roomId: 'f2-entry' },
      { id: 'f2-theater-table', type: 'organ-pump', anchor: [17, 7], size: [3.6, 4.2, 3], material: 'flesh-steel', animated: 'pulse', hero: true, roomId: 'f2-theater' },
      { id: 'f2-scrub-sink', type: 'bone-throne', anchor: [27, 4], size: [2.6, 3, 2], material: 'bone-iron', animated: 'drip', roomId: 'f2-scrub' },
      { id: 'f2-ward-beds-w', type: 'rib-stack', anchor: [4, 17], size: [2, 3.6, 1.8], material: 'flesh-rust', animated: 'settle', roomId: 'f2-wardA' },
      { id: 'f2-ward-beds-e', type: 'rib-stack', anchor: [30, 17], size: [2, 3.6, 1.8], material: 'flesh-rust', animated: 'settle', roomId: 'f2-wardC' },
      { id: 'f2-drawer-cache', type: 'bone-throne', anchor: [11, 4], size: [2.2, 2.4, 1.8], material: 'bone-violet', animated: 'rattle', roomId: 'f2-drawer' },
    ],
    machinery: [
      { id: 'f2-lobe-winches', type: 'winch-bank', anchor: [17, 6], span: [3, 2], motion: 'counterweight', cables: 5 },
      { id: 'f2-shaft-lift', type: 'chain-lift', anchor: [18, 2], span: [2.6, 4], motion: 'ratchet', cables: 3 },
      { id: 'f2-west-bank', type: 'pump-bank', anchor: [3, 11], span: [1.6, 3], motion: 'throb', pipes: 3 },
      { id: 'f2-east-bank', type: 'pump-bank', anchor: [32, 11], span: [1.6, 3], motion: 'throb', pipes: 3 },
    ],
    lights: [
      light([18, 20], '#ff3d36', 3, 'entry'),
      light([17, 15], '#cc2c37', 2.4, 'hub'),
      light([6, 17], '#cc2c37', 1.6, 'ward-a'),
      light([6, 10], '#cc2c37', 1.6, 'ward-b'),
      light([28, 17], '#cc2c37', 1.6, 'ward-c'),
      light([28, 10], '#cc2c37', 1.6, 'ward-d'),
      light([17, 7], '#ff6b40', 3.8, 'theater'),
      light([27, 4], '#ffad55', 2.8, 'scrub'),
      light([18, 2], '#ffad55', 3, 'exit'),
      light([11, 4], '#43c98a', 1.4, 'secret'),
    ],
    spots: [
      [0, 16, 21, 'stalker'], [0, 20, 21, 'caster'],
      [1, 16, 15, 'skitter'], [1, 19, 14, 'bloodhound'], [1, 17, 13, 'hexer'],
      [2, 6, 17, 'skitter'], [2, 6, 10, 'bloodhound'], [2, 28, 17, 'skitter'],
      [3, 28, 10, 'brute'], [3, 15, 6, 'brute'], [3, 19, 8, 'hexer'], [3, 21, 9, 'bloodhound'],
    ].map(([id, x, z, variant]) => ({ id: `f2-spawn-${id}`, x, z, wave: id, variant })),
    dread: 'Sterile light, wet floors. Every ward is occupied and none of the beds are breathing.',
    props: [
      prop('f2-gore-theater', 'gore', [17, 7], 9, 4),
      prop('f2-corpses-wardA', 'corpse', [6, 17], 4, 2),
      prop('f2-corpses-wardB', 'corpse', [6, 10], 4, 2),
      prop('f2-corpses-wardC', 'corpse', [28, 17], 4, 2),
      prop('f2-corpses-wardD', 'corpse', [28, 10], 4, 2),
      prop('f2-drawers', 'crate', [11, 4], 4, 2),
      prop('f2-candles-scrub', 'candle', [27, 4], 3, 2),
      prop('f2-webs-westloop', 'webs', [3, 12], 4, 3),
      prop('f2-fog-hub', 'fog', [17, 15], 3, 5),
      trail('f2-trail-eastloop', 'blood', [[32, 16], [33, 9]], 16),
      trail('f2-trail-hub', 'blood', [[14, 15], [22, 15]], 12),
      prop('f2-sigil-theater', 'sigil', [17, 6], 1, 1),
      prop('f2-skulls-drawer', 'skull', [11, 4], 4, 2),
      prop('f2-skulls-scrub', 'skull', [26, 4], 4, 2.5),
      prop('f2-eyes-wardB', 'eyes', [6, 11], 2, 2),
      prop('f2-eyes-vent', 'eyes', [13, 4], 2, 1.2),
      prop('f2-limbs-theater', 'limb', [17, 8], 6, 3),
      prop('f2-limbs-eastloop', 'limb', [32, 12], 4, 3),
      prop('f2-altar-theater', 'altar', [20, 8], 1, 1),
      prop('f2-bodypile-theater', 'bodypile', [17, 6], 6, 3),
      prop('f2-bodypile-wardA', 'bodypile', [6, 17], 4, 2.6),
      prop('f2-bodypile-wardD', 'bodypile', [28, 10], 4, 2.6),
      prop('f2-bloodpile-hub', 'bloodpile', [17, 15], 5, 4),
      prop('f2-barrels-scrub', 'barrel', [26, 5], 4, 2.4),
    ],
    signature: 'Sterile ward gone septic: gurneys, drawer morgues and theatre tables stacked with the surgery that failed.',
    wallpaper: 'sterile tile gone grey, handprints dragging toward every door, drains ringed with old blood',
    scares: [
      scare('f2-lights-theater', 'lights-out', [17, 7], 'Theater lights die on entry; only the table lamp survives.', { roomId: 'f2-theater' }),
      scare('f2-mimic-table', 'mimic', [17, 7], 'The surgery table breathes once when you turn your back.', { roomId: 'f2-theater' }),
      scare('f2-swarm-wardC', 'swarm', [28, 17], 'Ward C curtains snap open and the room empties at you.', { roomId: 'f2-wardC' }),
      scare('f2-hunt-hub', 'hunt', [17, 15], 'Clearing the crossing releases one bloodhound that never loses the trail.', { roomId: 'f2-hub' }),
      scare('f2-watcher-drawer', 'watcher', [11, 4], 'Through the vent: a face in the drawer that stays exactly where it is.', { roomId: 'f2-drawer' }),
      scare('f2-collapse-exit', 'collapse', [18, 5], 'The shaft gantry drops behind you once the key turns.', { roomId: 'f2-exit' }),
    ],
    setpieces: [
      piece('f2-sp-intake-tunnel', 'tunnel', { points: [[18, 19], [18, 17]], width: 2.2, height: 5, cue: 'red' }),
      piece('f2-sp-theater-door', 'pressure-door', { anchor: [17, 12], width: 2.4, height: 5, cue: 'red' }),
      piece('f2-sp-scrub-bulkhead', 'bulkhead', { anchor: [24, 7], width: 2.2, height: 4.4, cue: 'amber' }),
      piece('f2-sp-loop-collapse', 'collapse', { anchor: [33, 12], size: [1.6, 1.4, 1.4], cue: 'amber' }),
      piece('f2-sp-vent-hatch', 'recovery-cluster', { anchor: [13, 4], width: 1.6, height: 4.2, cue: 'amber' }),
    ],
    connections: [
      { id: 'f2-to-f3', kind: 'stair', at: [18.5, 2], to: 'f3-catacombs', label: 'Stair · Floor 03' },
    ],
  },

  // ---------------------------------------------------------------------------
  // FLOOR 03 — THE CATACOMBS
  // A three-lane lattice: two long cross corridors plus stems down to the
  // south lattice, with the reliquary court sealed in the middle and a hidden
  // tomb behind the colonnade.
  {
    id: 'f3-catacombs',
    index: 2,
    depth: 3,
    name: 'The Catacombs',
    tag: 'FLOOR 03 // THE DEAD ARE LOAD-BEARING',
    act: 'Act II',
    theme: 'ossuary',
    color: '#c98cff',
    width: 38,
    height: 26,
    entry: { x: 19.5, z: 23.5, angle: -Math.PI / 2 },
    exit: { x: 19.5, z: 2.5 },
    rooms: [
      room('f3-entry', 'Bone Gate', 'entry', [16, 22, 7, 3], {
        encounter: { tier: 2, budget: 7, maxAlive: 5, composition: { bloodhound: 2, skitter: 1 }, tactic: 'Read the rib gate before entering the lattice.' },
      }),
      room('f3-hub', 'Rib Colonnade', 'hub', [15, 14, 10, 4], {
        coverPatterns: ['colonnade'],
        encounter: { tier: 3, budget: 11, maxAlive: 6, composition: { brute: 1, bloodhound: 2, caster: 2 }, tactic: 'The colonnade is the crossroads for both crypt loops.' },
      }),
      room('f3-cryptW', 'West Crypt', 'ward', [2, 10, 6, 6], {
        coverPatterns: ['pillars'],
        encounter: { tier: 3, budget: 9, maxAlive: 5, composition: { skitter: 2, hexer: 1, caster: 1 }, tactic: 'Pillars break the ranged lanes.' },
      }),
      room('f3-cryptE', 'East Crypt', 'ward', [30, 10, 6, 6], {
        coverPatterns: ['pillars'],
        encounter: { tier: 3, budget: 9, maxAlive: 5, composition: { skitter: 2, hexer: 1, caster: 1 }, tactic: 'Mirror of the west crypt.' },
      }),
      room('f3-court', 'Reliquary Court', 'arena', [15, 5, 9, 6], {
        coverPatterns: ['center', 'corners'],
        hero: true,
        encounter: { tier: 5, budget: 18, maxAlive: 7, composition: { bellwraith: 1, warden: 1, bloodhound: 2, hexer: 1 }, tactic: 'Break the reliquary rhythm; both side arches stay open as escape lanes.' },
      }),
      room('f3-vault', 'Bone Vault', 'vault', [2, 2, 7, 5], {
        coverPatterns: [{ type: 'ring', inset: 1, step: 2 }],
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { caster: 2, skitter: 1 }, tactic: 'The reliquary key is walled into the bone vault.' },
      }),
      room('f3-niche', 'Skull Niche', 'side', [30, 2, 6, 5], {
        coverPatterns: ['corners'],
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { bloodhound: 2, hexer: 1 }, tactic: 'The east approach to the court.' },
      }),
      room('f3-ossuaryS', 'Drowned Ossuary', 'side', [2, 20, 6, 4], {
        coverPatterns: [{ type: 'edge', side: 'n', run: 3 }],
        encounter: { tier: 2, budget: 6, maxAlive: 4, composition: { skitter: 2, caster: 1 }, tactic: 'Flooded lower shelf off the south lattice.' },
      }),
      room('f3-stores', 'Charnel Stores', 'side', [30, 20, 6, 4], {
        coverPatterns: ['rows'],
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { bloodhound: 2, brute: 1 }, tactic: 'Stacked bone crates create short sightlines.' },
      }),
      room('f3-tomb', 'Hidden Tomb', 'secret', [25, 18, 3, 3], {
        note: 'Sealed tomb behind the colonnade vent.',
        reward: 'max health shard',
      }),
      room('f3-apse', 'Bell Apse', 'exit', [16, 1, 7, 3], {
        exitApproach: true,
        encounter: { tier: 1, budget: 0, maxAlive: 0, composition: {}, tactic: 'Ring the apse and take the stair to the choir.' },
      }),
    ],
    corridors: [
      corr('f3-c-south', [[19, 21], [19, 18]], 2.6, 'hall'),
      corr('f3-c-lat-south', [[30, 20], [19, 20], [8, 20]], 2.4, 'loop'),
      corr('f3-c-west-stem', [[4, 16], [4, 20], [8, 20]], 2.2, 'loop'),
      corr('f3-c-east-stem', [[33, 16], [33, 20], [30, 20]], 2.2, 'loop'),
      corr('f3-c-lat-mid', [[9, 12], [29, 12]], 2.4, 'loop'),
      corr('f3-c-court-s', [[19, 13], [19, 11]], 2.6, 'hall'),
      // Both side rooms branch from the court before its key-locked north gate.
      corr('f3-c-lat-north-w', [[9, 4], [13, 4], [13, 7], [14, 7]], 2.4, 'loop'),
      corr('f3-c-lat-north-e', [[24, 7], [25, 7], [25, 4], [29, 4]], 2.4, 'loop'),
      corr('f3-c-apse', [[19, 5], [19, 4]], 2.6, 'hall'),
      corr('f3-c-tomb-vent', [[25, 17], [25, 17]], 1.6, 'vent'),
    ],
    openings: [
      open('f3-o-entry-n', 'f3-entry', 'n', 19, 4),
      open('f3-o-hub-s', 'f3-hub', 's', 19, 4),
      open('f3-o-hub-n-w', 'f3-hub', 'n', 16, 3),
      open('f3-o-hub-n-c', 'f3-hub', 'n', 19, 4),
      open('f3-o-hub-n-e', 'f3-hub', 'n', 23, 3),
      open('f3-o-court-s', 'f3-court', 's', 19, 4, 'door', { lockedBy: 'room-clear' }),
      open('f3-o-court-w', 'f3-court', 'w', 7, 3),
      open('f3-o-court-e', 'f3-court', 'e', 7, 3),
      open('f3-o-court-n', 'f3-court', 'n', 19, 3, 'gate', { key: 'f3-reliquary-key', lockedBy: 'key' }),
      open('f3-o-apse-s', 'f3-apse', 's', 19, 3),
      open('f3-o-cryptW-e', 'f3-cryptW', 'e', 12, 3),
      open('f3-o-cryptE-w', 'f3-cryptE', 'w', 12, 3),
      open('f3-o-cryptW-s', 'f3-cryptW', 's', 4, 3),
      open('f3-o-cryptE-s', 'f3-cryptE', 's', 33, 3),
      open('f3-o-ossuary-e', 'f3-ossuaryS', 'e', 21, 3),
      open('f3-o-stores-w', 'f3-stores', 'w', 21, 3),
      open('f3-o-vault-e', 'f3-vault', 'e', 4, 3),
      open('f3-o-niche-w', 'f3-niche', 'w', 4, 3),
      open('f3-o-hub-vent', 'f3-hub', 'e', 17, 1, 'vent', { secret: true }),
      open('f3-o-tomb-n', 'f3-tomb', 'n', 26, 1),
    ],
    keys: [
      { id: 'f3-reliquary-key', name: 'Reliquary Key', at: [5, 4], roomId: 'f3-vault', opens: ['f3-o-court-n'], note: 'Opens the apse gate above the court.' },
    ],
    landmarks: [
      { id: 'f3-bone-threshold', type: 'rib-gate', anchor: [19, 23], size: [4.8, 2.6, 1.3], material: 'bone-iron', animated: 'rattle', playerFacing: true, roomId: 'f3-entry' },
      { id: 'f3-bone-reliquary', type: 'bone-throne', anchor: [19, 8], size: [3.8, 4.2, 3.2], material: 'bone-violet', animated: 'resonate', hero: true, roomId: 'f3-court' },
      { id: 'f3-colonnade-w', type: 'rib-stack', anchor: [17, 16], size: [2, 4.4, 2], material: 'bone-violet', animated: 'settle', roomId: 'f3-hub' },
      { id: 'f3-colonnade-e', type: 'rib-stack', anchor: [22, 16], size: [2, 4.4, 2], material: 'bone-violet', animated: 'settle', roomId: 'f3-hub' },
      { id: 'f3-vault-cage', type: 'bone-throne', anchor: [5, 4], size: [3, 3.4, 2.4], material: 'bone-violet', animated: 'resonate', roomId: 'f3-vault' },
      { id: 'f3-apse-bells', type: 'bell-array', anchor: [19, 2], size: [4.1, 4.2, 2.6], material: 'bone-brass', animated: 'ring', hero: true, roomId: 'f3-apse' },
      { id: 'f3-niche-skulls', type: 'rib-stack', anchor: [32, 4], size: [2.2, 3.4, 1.8], material: 'bone-violet', animated: 'settle', roomId: 'f3-niche' },
      { id: 'f3-stores-rack', type: 'tooth-rack', anchor: [32, 22], size: [2.2, 3.4, 1.8], material: 'bone-orange', animated: 'chatter', roomId: 'f3-stores' },
    ],
    machinery: [
      { id: 'f3-crypt-lift-w', type: 'chain-lift', anchor: [3, 12], span: [2, 4], motion: 'ratchet', cables: 3 },
      { id: 'f3-crypt-lift-e', type: 'chain-lift', anchor: [35, 12], span: [2, 4], motion: 'ratchet', cables: 3 },
      { id: 'f3-reliquary-winches', type: 'winch-bank', anchor: [19, 10], span: [3.4, 2.2], motion: 'counterweight', cables: 5 },
      { id: 'f3-apse-chandelier', type: 'bone-chandelier', anchor: [19, 2.4], span: [2.8, 2.8], motion: 'sway', payload: 'skulls' },
    ],
    lights: [
      light([19, 22], '#6d4dff', 3, 'entry'),
      light([19, 15], '#7e5dff', 2.4, 'hub'),
      light([5, 12], '#7e5dff', 1.8, 'crypt-west'),
      light([33, 12], '#7e5dff', 1.8, 'crypt-east'),
      light([19, 8], '#d5b7ff', 3.8, 'court'),
      light([5, 4], '#a476ff', 2.6, 'vault'),
      light([33, 4], '#7e5dff', 1.8, 'niche'),
      light([5, 22], '#7e5dff', 1.6, 'ossuary'),
      light([33, 22], '#7e5dff', 1.6, 'stores'),
      light([19, 2], '#c98cff', 3.4, 'apse'),
      light([26, 19], '#43c98a', 1.4, 'secret'),
    ],
    spots: [
      [0, 17, 23, 'bloodhound'], [0, 21, 23, 'skitter'],
      [1, 16, 16, 'brute'], [1, 22, 15, 'caster'], [1, 19, 14, 'bloodhound'],
      [2, 4, 12, 'skitter'], [2, 33, 12, 'skitter'], [2, 5, 22, 'caster'],
      [3, 33, 22, 'bloodhound'], [3, 32, 4, 'brute'], [3, 7, 4, 'caster'],
      [4, 17, 7, 'bellwraith'], [4, 21, 9, 'warden'], [4, 19, 6, 'hexer'],
    ].map(([id, x, z, variant]) => ({ id: `f3-spawn-${id}`, x, z, wave: id, variant })),
    dread: 'The walls are stacked with the dead and the stacks are load-bearing. Count the skulls and they count you back.',
    props: [
      prop('f3-bones-lattice', 'bones', [19, 20], 8, 5),
      prop('f3-bones-hub', 'bones', [19, 15], 6, 4),
      prop('f3-bones-court', 'bones', [19, 8], 8, 4),
      prop('f3-skulls-apse', 'bones', [19, 2], 6, 3),
      prop('f3-skulls-niche', 'bones', [32, 4], 5, 3),
      prop('f3-corpses-ossuary', 'corpse', [4, 21], 3, 2),
      prop('f3-candles-apse', 'candle', [19, 2], 5, 3),
      prop('f3-webs-tomb', 'webs', [26, 19], 4, 2),
      prop('f3-sigil-court', 'sigil', [19, 8], 1, 1),
      prop('f3-fog-cryptW', 'fog', [5, 12], 3, 4),
      prop('f3-fog-cryptE', 'fog', [33, 12], 3, 4),
      trail('f3-trail-lattice', 'blood', [[19, 19], [8, 20], [4, 16]], 18),
      prop('f3-skulls-hub', 'skull', [19, 16], 7, 4),
      prop('f3-skulls-niche', 'skull', [33, 4], 6, 3),
      prop('f3-skulls-apse', 'skull', [17, 2], 5, 2.5),
      prop('f3-eyes-cryptW', 'eyes', [4, 13], 3, 2),
      prop('f3-eyes-cryptE', 'eyes', [34, 13], 3, 2),
      prop('f3-eyes-tomb', 'eyes', [26, 19], 2, 1.4),
      prop('f3-limbs-court', 'limb', [19, 9], 6, 4),
      prop('f3-limbs-stores', 'limb', [32, 21], 4, 3),
      prop('f3-altar-apse', 'altar', [19, 2], 1, 1),
      prop('f3-bonepile-lattice', 'bones', [19, 20], 10, 6),
      prop('f3-bonepile-crypts', 'bones', [5, 12], 8, 4),
      prop('f3-bodypile-court', 'bodypile', [17, 7], 5, 3),
      prop('f3-bloodpile-court', 'bloodpile', [21, 9], 5, 4),
    ],
    signature: 'Catacomb lattice: stacked bone walls, skull inlay everywhere, no oil and no machines — only the dead.',
    wallpaper: 'stacked bone walls with skull inlay, crypt niches packed with femurs, candle soot above the arches',
    scares: [
      scare('f3-swarm-crypts', 'swarm', [5, 12], 'Both crypts empty at once through the pillar lanes.', { roomId: 'f3-cryptW' }),
      scare('f3-lights-lattice', 'lights-out', [19, 12], 'The lattice candles gutter out lane by lane behind you.', { roomId: 'f3-hub' }),
      scare('f3-scream-apse', 'scream', [19, 2], 'Every bell rings once, out of order.', { roomId: 'f3-apse' }),
      scare('f3-collapse-stores', 'collapse', [33, 22], 'The charnel stacks shift and cut the middle aisle.', { roomId: 'f3-stores' }),
      scare('f3-watcher-tomb', 'watcher', [26, 19], 'A skull on the tomb shelf tracks you and nothing else in the room moves.', { roomId: 'f3-tomb' }),
      scare('f3-hunt-court', 'hunt', [19, 8], 'The reliquary key wakes the warden that has been kneeling in the court.', { roomId: 'f3-court' }),
    ],
    setpieces: [
      piece('f3-sp-entry-bone-gate', 'tunnel', { points: [[19, 22], [19, 20]], width: 2.3, height: 5.2, cue: 'amber' }),
      piece('f3-sp-lattice-tunnel', 'tunnel', { points: [[8, 20], [30, 20]], width: 2.3, height: 5.2, cue: 'amber' }),
      piece('f3-sp-mid-tunnel', 'tunnel', { points: [[9, 12], [29, 12]], width: 2.3, height: 5.2, cue: 'amber' }),
      piece('f3-sp-court-bulkhead', 'bulkhead', { anchor: [19, 11], width: 2.6, height: 4.6, cue: 'red' }),
      piece('f3-sp-vault-pressure', 'pressure-door', { anchor: [9, 4], width: 2, height: 5, cue: 'red' }),
      piece('f3-sp-tomb-collapse', 'collapse', { anchor: [25, 17], size: [1.8, 1.5, 1.5], cue: 'amber' }),
      piece('f3-sp-apse-bulkhead', 'bulkhead', { anchor: [19, 4], width: 2.6, height: 4.6, cue: 'amber' }),
    ],
    connections: [
      { id: 'f3-to-f4', kind: 'stair', at: [19.5, 2], to: 'f4-resonance', label: 'Stair · Floor 04' },
    ],
  },

  // ---------------------------------------------------------------------------
  // FLOOR 04 — RESONANCE
  // A cathedral plan: long nave spine, two side aisles that loop around the
  // court, a bell tower holding the key and a hidden reliquary niche.
  {
    id: 'f4-resonance',
    index: 3,
    depth: 4,
    name: 'Resonance',
    tag: 'FLOOR 04 // EVERY BELL IS A MOUTH',
    act: 'Act III',
    theme: 'choir',
    color: '#ffb15e',
    width: 34,
    height: 24,
    entry: { x: 17.5, z: 21.5, angle: -Math.PI / 2 },
    exit: { x: 17.5, z: 1.5 },
    rooms: [
      room('f4-entry', 'Throat Gate', 'entry', [13, 20, 8, 3], {
        encounter: { tier: 3, budget: 10, maxAlive: 6, composition: { bloodhound: 2, bellwraithEcho: 1, skitter: 2 }, tactic: 'Hold the throat and read both aisles.' },
      }),
      room('f4-nave', 'Bell Nave', 'hub', [13, 13, 8, 6], {
        coverPatterns: ['colonnade'],
        encounter: { tier: 4, budget: 14, maxAlive: 7, composition: { bellwraith: 1, hexer: 1, bloodhound: 2, caster: 1 }, tactic: 'The nave is the hinge; both aisles loop back into it.' },
      }),
      room('f4-aisleW', 'West Aisle', 'loop', [5, 10, 4, 10], {
        coverPatterns: [{ type: 'edge', side: 'w', run: 6, from: 11 }],
        encounter: { tier: 3, budget: 9, maxAlive: 5, composition: { skitter: 2, hexer: 1 }, tactic: 'A narrow aisle: no room to strafe wide.' },
      }),
      room('f4-aisleE', 'East Aisle', 'loop', [25, 10, 4, 10], {
        coverPatterns: [{ type: 'edge', side: 'e', run: 6, from: 11 }],
        encounter: { tier: 3, budget: 9, maxAlive: 5, composition: { skitter: 2, hexer: 1 }, tactic: 'Mirror of the west aisle.' },
      }),
      room('f4-court', 'Resonance Court', 'arena', [12, 6, 10, 6], {
        coverPatterns: ['center', 'corners'],
        hero: true,
        encounter: { tier: 5, budget: 20, maxAlive: 8, composition: { bellwraith: 2, warden: 1, mireSinger: 1, bloodhound: 1 }, tactic: 'The court reads as the choir mouth; break the ranged timing behind the altar.' },
      }),
      room('f4-tower', 'Bell Tower', 'vault', [2, 3, 6, 6], {
        coverPatterns: ['pillars'],
        encounter: { tier: 4, budget: 11, maxAlive: 6, composition: { bellwraith: 1, bloodhound: 2, caster: 1 }, tactic: 'The bell key hangs in the tower ring.' },
      }),
      room('f4-organ', 'Organ Loft', 'vault', [26, 3, 6, 6], {
        coverPatterns: [{ type: 'rows', every: 3, length: 3 }],
        encounter: { tier: 4, budget: 11, maxAlive: 6, composition: { mireSinger: 1, hexer: 1, skitter: 2 }, tactic: 'Pipe ranks give the loft its teeth.' },
      }),
      room('f4-chancel', 'Chancel', 'side', [13, 3, 8, 3], {
        coverPatterns: [{ type: 'edge', side: 'n', run: 4 }],
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { bloodhound: 2, caster: 1 }, tactic: 'Last stand before the descent gate.' },
      }),
      room('f4-niche', 'Reliquary Niche', 'secret', [29, 14, 3, 3], {
        note: 'Hidden niche behind the east aisle.',
        reward: 'weapon cache',
      }),
      room('f4-exit', 'Descent Mouth', 'exit', [14, 0, 7, 3], {
        exitApproach: true,
        encounter: { tier: 1, budget: 0, maxAlive: 0, composition: {}, tactic: 'The last descent begins here.' },
      }),
    ],
    corridors: [
      corr('f4-c-nave', [[17, 19], [17, 19]], 2.6, 'hall'),
      corr('f4-c-aisle-w-s', [[12, 21], [12, 19], [9, 19]], 2.2, 'loop'),
      corr('f4-c-aisle-e-s', [[22, 21], [22, 19], [24, 19]], 2.2, 'loop'),
      corr('f4-c-aisle-w-n', [[9, 11], [11, 11]], 2.2, 'loop'),
      corr('f4-c-aisle-e-n', [[22, 9], [24, 9]], 2.2, 'loop'),
      corr('f4-c-court-chancel', [[17, 5], [17, 5]], 2.6, 'hall'),
      corr('f4-c-chancel-exit', [[17, 2], [17, 2]], 2.6, 'hall'),
      corr('f4-c-niche', [[28, 15], [28, 15]], 1.6, 'vent'),
    ],
    openings: [
      open('f4-o-entry-n', 'f4-entry', 'n', 17, 4),
      open('f4-o-nave-s', 'f4-nave', 's', 17, 4),
      open('f4-o-entry-w', 'f4-entry', 'w', 21, 3),
      open('f4-o-aisleW-s', 'f4-aisleW', 's', 19, 3),
      open('f4-o-entry-e', 'f4-entry', 'e', 21, 3),
      open('f4-o-aisleE-s', 'f4-aisleE', 's', 19, 3),
      open('f4-o-nave-n', 'f4-nave', 'n', 17, 4),
      open('f4-o-court-s', 'f4-court', 's', 17, 4, 'door', { lockedBy: 'room-clear' }),
      open('f4-o-court-w', 'f4-court', 'w', 11, 3),
      open('f4-o-aisleW-n', 'f4-aisleW', 'n', 11, 3),
      open('f4-o-court-e', 'f4-court', 'e', 9, 3),
      open('f4-o-aisleE-n', 'f4-aisleE', 'n', 9, 3),
      open('f4-o-court-n', 'f4-court', 'n', 17, 4),
      open('f4-o-chancel-s', 'f4-chancel', 's', 17, 4),
      open('f4-o-chancel-n', 'f4-chancel', 'n', 17, 3, 'gate', { key: 'f4-bell-key', lockedBy: 'key' }),
      open('f4-o-exit-s', 'f4-exit', 's', 17, 3),
      open('f4-o-tower-s', 'f4-tower', 's', 4, 3),
      open('f4-o-aisleW-h', 'f4-aisleW', 'n', 6, 3),
      open('f4-o-organ-s', 'f4-organ', 's', 28, 3),
      open('f4-o-aisleE-h', 'f4-aisleE', 'n', 26, 3),
      open('f4-o-aisleE-vent', 'f4-aisleE', 'e', 15, 1, 'vent', { secret: true }),
      open('f4-o-niche-w', 'f4-niche', 'w', 15, 1),
    ],
    keys: [
      { id: 'f4-bell-key', name: 'Bell Key', at: [4, 5], roomId: 'f4-tower', opens: ['f4-o-chancel-n'], note: 'Opens the descent gate in the chancel.' },
    ],
    landmarks: [
      { id: 'f4-throat-gate', type: 'mouth-gate', anchor: [17, 21], size: [4.7, 2.4, 1.5], material: 'flesh-brass', animated: 'breathe', playerFacing: true, roomId: 'f4-entry' },
      { id: 'f4-mouth-altar', type: 'mouth-altar', anchor: [17, 8], size: [4.2, 4.3, 3.5], material: 'flesh-gold', animated: 'sing', hero: true, roomId: 'f4-court' },
      { id: 'f4-nave-bells', type: 'bell-array', anchor: [17, 15], size: [3.6, 3.6, 2.2], material: 'brass-flesh', animated: 'ring', roomId: 'f4-nave' },
      { id: 'f4-tower-ring', type: 'bell-array', anchor: [5, 5], size: [3.4, 3.6, 2.4], material: 'bone-brass', animated: 'ring', roomId: 'f4-tower' },
      { id: 'f4-organ-pipes', type: 'tooth-rack', anchor: [28, 5], size: [3.4, 3.8, 2], material: 'bone-orange', animated: 'chatter', roomId: 'f4-organ' },
      { id: 'f4-chancel-teeth', type: 'mouth-gate', anchor: [17, 4], size: [3.6, 2.2, 1.4], material: 'flesh-brass', animated: 'breathe', roomId: 'f4-chancel' },
      { id: 'f4-exit-nave', type: 'bell-array', anchor: [17, 1], size: [4.4, 4.1, 2.8], material: 'brass-flesh', animated: 'ring', hero: true, roomId: 'f4-exit' },
    ],
    machinery: [
      { id: 'f4-organ-west', type: 'pipe-organ', anchor: [6, 11], span: [2, 5], motion: 'breath', pipes: 6 },
      { id: 'f4-organ-east', type: 'pipe-organ', anchor: [28, 11], span: [2, 5], motion: 'breath', pipes: 6 },
      { id: 'f4-court-winches', type: 'bell-winches', anchor: [17, 10], span: [3.4, 2], motion: 'counterweight', cables: 5 },
      { id: 'f4-nave-chandelier', type: 'bell-chandelier', anchor: [17, 14], span: [3, 3], motion: 'sway', payload: 'bells' },
    ],
    lights: [
      light([17, 20], '#e35b2b', 3, 'entry'),
      light([17, 15], '#d2452b', 2.4, 'nave'),
      light([6, 15], '#d2452b', 1.8, 'aisle-west'),
      light([27, 15], '#d2452b', 1.8, 'aisle-east'),
      light([17, 8], '#ffd06b', 4, 'court'),
      light([5, 5], '#ffb15e', 3, 'tower'),
      light([28, 5], '#ff9a48', 2.6, 'organ'),
      light([17, 4], '#ffd06b', 2.6, 'chancel'),
      light([17, 1], '#ffb15e', 3.4, 'exit'),
      light([30, 15], '#43c98a', 1.4, 'secret'),
    ],
    spots: [
      [0, 14, 21, 'bloodhound'], [0, 20, 21, 'skitter'],
      [1, 15, 15, 'bellwraithEcho'], [1, 19, 17, 'hexer'], [1, 17, 14, 'caster'],
      [2, 6, 12, 'skitter'], [2, 27, 12, 'skitter'], [2, 6, 18, 'hexer'],
      [3, 27, 18, 'mireSinger'], [3, 7, 5, 'bellwraith'], [3, 28, 5, 'brute'],
      [4, 15, 8, 'bellwraith'], [4, 19, 9, 'warden'], [4, 17, 7, 'mireSinger'],
    ].map(([id, x, z, variant]) => ({ id: `f4-spawn-${id}`, x, z, wave: id, variant })),
    dread: 'The cathedral is singing to itself. Each bell is a mouth and every mouth has already swallowed someone.',
    props: [
      prop('f4-candles-nave', 'candle', [17, 15], 8, 4),
      prop('f4-candles-aisleW', 'candle', [6, 14], 5, 3),
      prop('f4-candles-aisleE', 'candle', [27, 14], 5, 3),
      prop('f4-gore-court', 'gore', [17, 8], 9, 4),
      prop('f4-bones-tower', 'bones', [5, 5], 6, 3),
      prop('f4-crates-organ', 'crate', [28, 5], 4, 3),
      prop('f4-webs-niche', 'webs', [30, 15], 4, 2),
      prop('f4-sigil-court', 'sigil', [17, 8], 1, 1),
      prop('f4-fog-aisleW', 'fog', [6, 12], 3, 5),
      prop('f4-fog-aisleE', 'fog', [27, 12], 3, 5),
      trail('f4-trail-nave', 'blood', [[17, 19], [17, 13]], 14),
      prop('f4-corpses-chancel', 'corpse', [17, 4], 3, 3),
      prop('f4-skulls-tower', 'skull', [5, 6], 5, 3),
      prop('f4-skulls-chancel', 'skull', [15, 4], 5, 3),
      prop('f4-eyes-aisleW', 'eyes', [6, 13], 3, 2),
      prop('f4-eyes-aisleE', 'eyes', [27, 13], 3, 2),
      prop('f4-limbs-nave', 'limb', [17, 17], 5, 4),
      prop('f4-limbs-court', 'limb', [14, 7], 5, 3),
      prop('f4-altar-court', 'altar', [20, 7], 1, 1),
      prop('f4-barrels-organ', 'barrel', [28, 6], 5, 2.6),
      prop('f4-bodypile-aisles', 'bodypile', [6, 14], 4, 2.6),
      prop('f4-bodypile-nave', 'bodypile', [15, 17], 4, 3),
      prop('f4-bloodpile-nave', 'bloodpile', [19, 16], 5, 4),
    ],
    signature: 'Cathedral of mouths: candle rows, brass bells and chandeliers, every wall panel a throat.',
    wallpaper: 'brass mouths set into the walls, teeth lines along the cornices, wet red light on every cantilever',
    scares: [
      scare('f4-lights-nave', 'lights-out', [17, 15], 'The nave goes black and every bell leans toward you at once.', { roomId: 'f4-nave' }),
      scare('f4-scream-court', 'scream', [17, 8], 'The mouth altar inhales and the aisles answer.', { roomId: 'f4-court' }),
      scare('f4-swarm-aisles', 'swarm', [6, 12], 'Both aisles disgorge at the same time, left and right.', { roomId: 'f4-aisleW' }),
      scare('f4-hunt-chancel', 'hunt', [17, 4], 'The last gate wakes a warden that walks the nave line.', { roomId: 'f4-chancel' }),
      scare('f4-watcher-niche', 'watcher', [30, 15], 'The reliquary niche is occupied and the occupant is patient.', { roomId: 'f4-niche' }),
      scare('f4-collapse-exit', 'collapse', [17, 2], 'The descent mouth folds shut behind you.', { roomId: 'f4-exit' }),
    ],
    setpieces: [
      piece('f4-sp-aisleW-tunnel', 'tunnel', { points: [[12, 21], [9, 19], [6, 12]], width: 2.1, height: 5, cue: 'amber' }),
      piece('f4-sp-aisleE-tunnel', 'tunnel', { points: [[22, 21], [24, 19], [27, 12]], width: 2.1, height: 5, cue: 'amber' }),
      piece('f4-sp-court-door', 'pressure-door', { anchor: [17, 12], width: 2.6, height: 5.2, cue: 'red' }),
      piece('f4-sp-cross-gallery', 'tunnel', { points: [[9, 11], [17, 11], [24, 9]], width: 2.2, height: 5, cue: 'amber' }),
      piece('f4-sp-chancel-bulkhead', 'bulkhead', { anchor: [17, 5], width: 2.6, height: 4.6, cue: 'red' }),
      piece('f4-sp-niche-hatch', 'recovery-cluster', { anchor: [28, 15], width: 1.6, height: 4.2, cue: 'amber' }),
    ],
    connections: [
      { id: 'f4-to-f5', kind: 'drop', at: [17.5, 1], to: 'f5-last-descent', label: 'Drop · Floor 05' },
    ],
  },

  // ---------------------------------------------------------------------------
  // FLOOR 05 — THE LAST DESCENT
  // Three tightening arenas joined by short throats, a side vault that hides
  // the final key, a sealed cache and the last chamber.
  {
    id: 'f5-last-descent',
    index: 4,
    depth: 5,
    name: 'The Last Descent',
    tag: 'FLOOR 05 // NO EXIT SIGNAL',
    act: 'Finale',
    theme: 'choir',
    color: '#ffd06b',
    width: 28,
    height: 22,
    entry: { x: 14.5, z: 19.5, angle: -Math.PI / 2 },
    exit: { x: 14.5, z: 1 },
    rooms: [
      room('f5-entry', 'Descent Mouth', 'entry', [10, 19, 8, 3], {
        encounter: { tier: 3, budget: 8, maxAlive: 5, composition: { bloodhound: 2, skitter: 1 }, tactic: 'No second wave here: the first arena is the teacher.' },
      }),
      room('f5-hall1', 'First Throat', 'arena', [9, 14, 10, 4], {
        coverPatterns: ['colonnade', 'corners'],
        encounter: { tier: 4, budget: 13, maxAlive: 6, composition: { brute: 2, bloodhound: 2, hexer: 1 }, tactic: 'Column pairs split the push into three lanes.' },
      }),
      room('f5-hall2', 'Second Throat', 'arena', [10, 8, 9, 4], {
        coverPatterns: ['center', { type: 'edge', side: 'n', run: 3 }],
        encounter: { tier: 5, budget: 17, maxAlive: 7, composition: { warden: 1, bellwraith: 1, bloodhound: 2, caster: 2 }, tactic: 'The centre block is the only safe pivot.' },
      }),
      room('f5-vault', 'Warden Vault', 'vault', [2, 9, 6, 6], {
        coverPatterns: ['pillars'],
        encounter: { tier: 4, budget: 10, maxAlive: 5, composition: { warden: 1, hexer: 1, skitter: 2 }, tactic: 'The final key is walled into the vault.' },
      }),
      room('f5-organ', 'Organ Chamber', 'vault', [20, 9, 6, 6], {
        coverPatterns: [{ type: 'rows', every: 2, length: 3 }],
        encounter: { tier: 5, budget: 15, maxAlive: 6, composition: { mireSinger: 1, hexer: 2, bloodhound: 1 }, tactic: 'Pipe rows make the chamber a ranged trap.' },
      }),
      room('f5-cache', 'Reliquary Cache', 'secret', [2, 4, 4, 3], {
        note: 'Sealed cache above the vault.',
        reward: 'max ammo',
      }),
      room('f5-hall3', 'Last Chamber', 'arena', [10, 2, 9, 5], {
        coverPatterns: ['ring', 'center'],
        hero: true,
        encounter: { tier: 6, budget: 22, maxAlive: 8, composition: { bellwraith: 2, warden: 2, mireSinger: 1, bloodhound: 2 }, tactic: 'Final stand: the ring cover is the last piece of ground you own.' },
      }),
      room('f5-exit', 'The Last Dead', 'exit', [12, 0, 5, 2], {
        exitApproach: true,
        encounter: { tier: 1, budget: 0, maxAlive: 0, composition: {}, tactic: 'Campaign end.' },
      }),
    ],
    corridors: [
      corr('f5-c-throat-1', [[14, 18], [14, 18]], 2.6, 'hall'),
      corr('f5-c-throat-2', [[14, 13], [14, 12]], 2.4, 'hall'),
      corr('f5-c-throat-3', [[14, 7], [14, 7]], 2.4, 'hall'),
      corr('f5-c-vault', [[9, 10], [8, 10]], 2.2, 'service'),
      corr('f5-c-cache-vent', [[3, 8], [3, 7]], 1.6, 'vent'),
      corr('f5-c-organ', [[19, 10], [20, 10]], 2.2, 'service'),
    ],
    openings: [
      open('f5-o-entry-n', 'f5-entry', 'n', 14, 4),
      open('f5-o-hall1-s', 'f5-hall1', 's', 14, 4),
      open('f5-o-hall1-n', 'f5-hall1', 'n', 14, 3, 'door', { lockedBy: 'room-clear' }),
      open('f5-o-hall2-s', 'f5-hall2', 's', 14, 3),
      open('f5-o-hall2-n', 'f5-hall2', 'n', 14, 3, 'door', { lockedBy: 'room-clear' }),
      open('f5-o-hall3-s', 'f5-hall3', 's', 14, 3),
      open('f5-o-hall3-n', 'f5-hall3', 'n', 14, 3, 'gate', { key: 'f5-warden-key', lockedBy: 'key' }),
      open('f5-o-exit-s', 'f5-exit', 's', 14, 3),
      open('f5-o-hall2-w', 'f5-hall2', 'w', 10, 3),
      open('f5-o-vault-e', 'f5-vault', 'e', 10, 3),
      open('f5-o-vault-n', 'f5-vault', 'n', 3, 2),
      open('f5-o-cache-s', 'f5-cache', 's', 3, 2, 'vent', { secret: true }),
      open('f5-o-hall2-e', 'f5-hall2', 'e', 10, 3),
      open('f5-o-organ-w', 'f5-organ', 'w', 10, 3),
    ],
    keys: [
      { id: 'f5-warden-key', name: 'Warden Key', at: [4, 11], roomId: 'f5-vault', opens: ['f5-o-hall3-n'], note: 'Opens the last chamber.' },
    ],
    landmarks: [
      { id: 'f5-entry-mouth', type: 'mouth-gate', anchor: [14, 20], size: [4.2, 2.2, 1.4], material: 'flesh-brass', animated: 'breathe', playerFacing: true, roomId: 'f5-entry' },
      { id: 'f5-first-rack', type: 'tooth-rack', anchor: [10, 15], size: [2.2, 3.6, 1.8], material: 'bone-orange', animated: 'chatter', roomId: 'f5-hall1' },
      { id: 'f5-mid-throat', type: 'mouth-gate', anchor: [14.5, 16], size: [4.9, 4.5, 2.8], material: 'flesh-brass', animated: 'breathe', roomId: 'f5-hall1' },
      { id: 'f5-second-altar', type: 'mouth-altar', anchor: [14.5, 10], size: [3.4, 3.6, 2.8], material: 'flesh-gold', animated: 'sing', roomId: 'f5-hall2' },
      { id: 'f5-warden-cage', type: 'bone-throne', anchor: [4, 11], size: [3, 3.4, 2.4], material: 'bone-violet', animated: 'resonate', roomId: 'f5-vault' },
      { id: 'f5-organ-ranks', type: 'tooth-rack', anchor: [23, 10], size: [3, 3.8, 2], material: 'bone-orange', animated: 'chatter', roomId: 'f5-organ' },
      { id: 'f5-last-altar', type: 'mouth-altar', anchor: [14.5, 4], size: [4.4, 4.6, 3.6], material: 'flesh-gold', animated: 'sing', hero: true, roomId: 'f5-hall3' },
      { id: 'f5-cache-relic', type: 'bone-throne', anchor: [4, 5], size: [2.4, 2.6, 1.8], material: 'bone-violet', animated: 'resonate', roomId: 'f5-cache' },
    ],
    machinery: [
      { id: 'f5-vault-lift', type: 'chain-lift', anchor: [4, 13], span: [2, 3], motion: 'ratchet', cables: 3 },
      { id: 'f5-organ-winches', type: 'bell-winches', anchor: [23, 13], span: [2.4, 2], motion: 'counterweight', cables: 4 },
      { id: 'f5-last-chandelier', type: 'bell-chandelier', anchor: [14, 3], span: [3, 3], motion: 'sway', payload: 'bells' },
      { id: 'f5-throat-hoist', type: 'hanging-hoist', anchor: [14, 12], span: [2, 2], motion: 'pendulum', payload: 'heart' },
    ],
    lights: [
      light([14, 20], '#e35b2b', 3, 'entry'),
      light([14, 16], '#d2452b', 2.6, 'hall-1'),
      light([14, 10], '#ffd06b', 3.4, 'hall-2'),
      light([4, 11], '#a476ff', 2.6, 'vault'),
      light([23, 11], '#ff9a48', 2.6, 'organ'),
      light([14, 4], '#ffd06b', 4.2, 'hall-3'),
      light([4, 5], '#43c98a', 1.4, 'secret'),
      light([14, 1], '#ffb15e', 3.4, 'exit'),
    ],
    spots: [
      [0, 12, 20, 'bloodhound'], [0, 16, 20, 'skitter'],
      [1, 10, 15, 'brute'], [1, 17, 16, 'bloodhound'], [1, 13, 15, 'hexer'],
      [2, 12, 9, 'warden'], [2, 17, 10, 'bellwraith'], [2, 11, 11, 'caster'],
      [3, 7, 11, 'warden'], [3, 22, 11, 'mireSinger'], [3, 24, 12, 'hexer'],
      [4, 12, 4, 'bellwraith'], [4, 16, 5, 'warden'], [4, 14, 3, 'mireSinger'],
    ].map(([id, x, z, variant]) => ({ id: `f5-spawn-${id}`, x, z, wave: id, variant })),
    dread: 'Three rooms left and each one is smaller than the last. The dead have stopped hiding.',
    props: [
      prop('f5-gore-hall1', 'gore', [14, 16], 8, 4),
      prop('f5-gore-hall2', 'gore', [14, 10], 9, 4),
      prop('f5-gore-hall3', 'gore', [14, 4], 12, 5),
      prop('f5-bones-vault', 'bones', [4, 11], 6, 3),
      prop('f5-corpses-organ', 'corpse', [23, 11], 4, 3),
      prop('f5-candles-cache', 'candle', [4, 5], 3, 2),
      prop('f5-cages-hall2', 'cage', [14, 9], 3, 3),
      prop('f5-sigil-hall3', 'sigil', [14, 4], 2, 2),
      prop('f5-fog-throat1', 'fog', [14, 13], 2, 4),
      prop('f5-fog-throat2', 'fog', [14, 7], 2, 4),
      trail('f5-trail-descent', 'blood', [[14, 18], [14, 3]], 20),
      prop('f5-skulls-vault', 'skull', [3, 12], 5, 3),
      prop('f5-skulls-hall3', 'skull', [16, 3], 7, 4),
      prop('f5-eyes-organ', 'eyes', [23, 10], 3, 2.5),
      prop('f5-eyes-exit', 'eyes', [14, 1], 2, 1.2),
      prop('f5-limbs-hall1', 'limb', [11, 16], 6, 4),
      prop('f5-limbs-hall3', 'limb', [12, 5], 7, 4),
      prop('f5-altar-last', 'altar', [16, 4], 1, 1),
      prop('f5-barrels-descent', 'barrel', [12, 18], 7, 3),
      prop('f5-bodypile-hall2', 'bodypile', [16, 10], 6, 3.4),
      prop('f5-bodypile-last', 'bodypile', [13, 3], 7, 3.6),
      prop('f5-bloodpile-last', 'bloodpile', [15, 5], 6, 4),
    ],
    signature: 'The last stand: the throat corridors are stacked with the previous waves and the floor no longer dries.',
    wallpaper: 'walls that flex when hit, brass mouths in the corners, everything slick and red under the last lights',
    scares: [
      scare('f5-hunt-hall1', 'hunt', [14, 16], 'The first throat closes and two brutes come through the columns.', { roomId: 'f5-hall1' }),
      scare('f5-lights-hall2', 'lights-out', [14, 10], 'Second throat: the chandelier drops and the room goes red.', { roomId: 'f5-hall2' }),
      scare('f5-swarm-organ', 'swarm', [23, 11], 'The organ chamber plays and something climbs out of the pipes.', { roomId: 'f5-organ' }),
      scare('f5-scream-hall3', 'scream', [14, 4], 'The last altar screams with a human voice.', { roomId: 'f5-hall3' }),
      scare('f5-watcher-exit', 'watcher', [14, 1], 'Past the last gate, the exit is already standing open for you.', { roomId: 'f5-exit' }),
      scare('f5-collapse-vault', 'collapse', [4, 13], 'Taking the warden key drops the vault ceiling on the way out.', { roomId: 'f5-vault' }),
    ],
    setpieces: [
      piece('f5-sp-throat1-tunnel', 'tunnel', { points: [[14.5, 17], [14.5, 13]], width: 2.2, height: 5, cue: 'red' }),
      piece('f5-sp-throat2-tunnel', 'tunnel', { points: [[14.5, 12], [14.5, 7]], width: 2.2, height: 5, cue: 'red' }),
      piece('f5-sp-throat3-tunnel', 'tunnel', { points: [[14.5, 7], [14.5, 3]], width: 2.3, height: 5.4, cue: 'amber' }),
      piece('f5-sp-vault-collapse', 'collapse', { anchor: [3, 8], size: [2, 1.6, 1.6], cue: 'amber' }),
      piece('f5-sp-last-bulkhead', 'bulkhead', { anchor: [14.5, 7], width: 2.8, height: 4.8, openingWidth: 5.8, cue: 'red' }),
      piece('f5-sp-cache-hatch', 'recovery-cluster', { anchor: [3, 7], width: 1.8, height: 4.4, cue: 'amber' }),
    ],
    connections: [
      { id: 'f5-end', kind: 'end', at: [14.5, 1], to: null, label: 'Campaign end' },
    ],
  },
]);

export const DUNGEON_SUMMARY = Object.freeze({
  layers: DUNGEON_LAYERS.length,
  rooms: DUNGEON_LAYERS.reduce((sum, layer) => sum + layer.rooms.length, 0),
  corridors: DUNGEON_LAYERS.reduce((sum, layer) => sum + layer.corridors.length, 0),
  openings: DUNGEON_LAYERS.reduce((sum, layer) => sum + layer.openings.length, 0),
  keys: DUNGEON_LAYERS.reduce((sum, layer) => sum + layer.keys.length, 0),
  secrets: DUNGEON_LAYERS.reduce((sum, layer) => sum + layer.rooms.filter(room => room.kind === 'secret').length, 0),
});
